### PR TITLE
Take a break from build copping for rest of quarter 🧘

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

I think it is my responsibility to contribute as a build cop, however
I've been finding it really hard to make the progress I'd like on
catalog (and pipelineresource) stuff so I want to take a break from
build copping, but only temporarily!

I ran the script twice to make this work, but I also needed to remove
the duplicate header that we ended with halfway through so its a bit
janky.

```
go run ./cmd/generate-rotation-csv \
    -names andrea.fritolli,wlynch,dibyo,nikthoma,sashture,sbws,jerop,vdemeest \
    --start-date 2020-07-07 -days 55 \
    --overrides rotation-overrides.csv > rotation.csv

go run ./cmd/generate-rotation-csv \
    -names andrea.fritolli,wlynch,christiewilson,dibyo,nikthoma,sashture,sbws,jerop,vdemeest \
    --start-date 2020-08-31 -days 152 \
    --overrides rotation-overrides.csv >> rotation.csv

```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
Let me know if the changes in dates cause any problems for you and you want me to add overrides for anything @vdemeester @afrittoli @dibyom @wlynch @sbwsg @savitaashture @nikhil-thomas

**Comment by afrittoli** [comment]
/lgtm
My name needs to be fixed by I can do that in a different PR :)

**Comment by bobcatfish** [comment]
> My name needs to be fixed by I can do that in a different PR :)

whoops, im happy to fix it!

**Comment by bobcatfish** [comment]
I think I've fixed it @afrittoli !

**Pull request merged**
