### PR TITLE
prow: disable go-coverage jobs on tektoncd/hub

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

The coverage tool doesn't handle very well when the go code is not on
the root of the repository, so disabling it on the hub. This is temporary.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @sthaha @afrittoli @bobcatfish @chmouel @nikhil-thomas 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
>  the root of the repository, so disabling it on the hub. This is temporary.

Are we going to move the go code to root eventually, or what will the solution be?

**Comment by vdemeester** [comment]
> Are we going to move the go code to root eventually, or what will the solution be?

Not sure yet but do not really want to block on this now :upside_down_face: I think long term is to control the `coverage` tool too (and simplify it :stuck_out_tongue: )

**Pull request merged**
