### PR TITLE
Fix postsubmit logs location

### PR DESCRIPTION
**Pull request by eddycharly**
Fixing #326

### CODE REVIEW

**Comment by sbwsg** [comment]
This looks sound to me but I have to confess I don't actually know if it's correct or not.  @dibyom, @afrittoli, or @vdemeester might know more?

**Comment by eddycharly** [comment]
It is correct, in fact it can be anything but it has to be consistent with the config here:
https://github.com/tektoncd/plumbing/blob/ba56b3c3a78bad79177b4730826d780ddcf36319/prow/config.yaml#L2

If you take this link for example https://tekton-releases.appspot.com/build/tekton-prow/logs/tekton-pipeline-publish-images/1250471362649133057/ and swap `logs` with `pr-logs` it works, this is the opposite of the fix ;-)

**Comment by sbwsg** [comment]
Ah I see.

So if the type is "presubmit" then we want to upload to `pr-logs` otherwise we want to upload to `logs`.

**Pull request merged**
