### PR TITLE
images/test-runner: update a bunch of tools

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Update a bunch of tools in `test-runner` image.
- ko to 0.15.3
- golangci-lint to 1.56.2
- kustomize to 5.3.0
- yq to 4.42.1

Each update is in its own commit to facilitate if we need to revert any bump.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
Hopefully things won't break, anyways versions are pinned so it should be fine.
/approve

**Comment by vdemeester** [comment]
> Hopefully things won't break, anyways versions are pinned so it should be fine. /approve

Yeah, that's kind of what makes me not worry. But the `golangci-lint` bump is most likely gonna require some, adjustements on each repositories… The good thing is, we can decide "when" we want to do it, per repositories.

**Review by JeromeJu — APPROVED** [review]

**Review by dibyom — APPROVED** [review]

**Pull request merged**
