### PR TITLE
Safe back to latest

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Migrate prow jobs back to `:latest`. I did split it into several commit if we don't wanna dare do it all at once but switch repository from repository :stuck_out_tongue: 

/cc @afrittoli 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
Go for it, worst case we can revert one of the commits

**Comment by bobcatfish** [comment]
🙏 as someone who jumps in and out of plumbing, and also who loves to dig through the history of how things happened and why, is it possible to include some more info in this PR (and/or a linked issue?) about why we were using "safe", what went wrong, why "latest" is okay now? 🙏

**Comment by vdemeester** [comment]
> pray as someone who jumps in and out of plumbing, and also who loves to dig through the history of how things happened and why, is it possible to include some more info in this PR (and/or a linked issue?) about why we were using "safe", what went wrong, why "latest" is okay now? pray

So a few days (or a little bit more than a week) I broke the whole CI and the fix was to tag the latest know valid image as `:safe` and update the prow job with it https://github.com/tektoncd/plumbing/pull/313. 

The reason it got broken is a bit fishy :sweat_smile: We went ahead on owning the whole image ourselves (https://github.com/tektoncd/plumbing/pull/295) and did a few cleaning on it https://github.com/tektoncd/plumbing/pull/310. Some tools from here (`kubetest`, …) where thus rebuild on really recent image and their behaviour broke :sweat_smile:. 

After *getting `:safe`*, we cleaned some more (https://github.com/tektoncd/plumbing/pull/315, https://github.com/tektoncd/plumbing/pull/341, https://github.com/tektoncd/plumbing/pull/348, https://github.com/tektoncd/plumbing/pull/349) and tried it out on the experimental repository. It should be now good to go :pray:

**Pull request merged**
