### PR TITLE
Ignore warnings when deploying resources

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

The deployment template fails if there is a Warning in the log file.

Fixes: #932

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by dibyom — APPROVED** [review]
/lgtm

**Comment by afrittoli** [comment]
@tektoncd/plumbing-maintainers can I have an lgtm on this which will restore resource deployment 🙏

**Pull request merged**
