### PR TITLE
Add afrittoli and dibyom to owners

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

:angel:

/cc @bobcatfish 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
/hold
(for @bobcatfish 's review)

**Comment by bobcatfish** [comment]
Yep totally good with this! The only thing that's been blocking me from proposing this is I want to update our policy in https://github.com/tektoncd/plumbing/blob/master/CONTRIBUTING.md as well to say that anyone who is an OWNER in another tektoncd repo is eligible to be an OWNER here. But we can add that later!

/lgtm

**Comment by bobcatfish** [comment]
image

**Pull request merged**
