### PR TITLE
Move Dashboard integration tests from GKE to Kind

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
@tektoncd/plumbing-maintainers please review

**Comment by abayer** [comment]
/approve

Looks good! Hopefully my migration doc was accurate and this just works. =)

**Comment by AlanGreene** [comment]
/hold
hrmm, digging into this a bit more I think it will actually fail at https://github.com/tektoncd/plumbing/blob/5d5152b72f966ad0fda5119ea28ba2ac03cce8bc/tekton/images/test-runner/setup-kind.sh#L314 as we're passing `"./test/presubmit-tests.sh --integration-tests"` which is not a valid command.

@abayer Any objections to removing the surrounding quotes in the script? The only down side I see is that folks using paths containing spaces would need to ensure they're properly escaped in prow/config.yaml rather than relying on the script handling it.

**Comment by abayer** [comment]
Aaaaah, you've got pre-integration stuff to run in `presubmit-tests.sh` - Pipeline doesn't, so we can just call `./test/e2e-tests.sh` directly. Yeah, I think a wrapper script would probably be cleanest.

**Comment by AlanGreene** [comment]
Should be good to go now 🤞
/hold cancel

**Pull request merged**
