### PR TITLE
Nest Results Ingress in dogfooding folder.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Nest Results Ingress in dogfooding folder, based on feedback in https://github.com/tektoncd/plumbing/pull/834#issuecomment-839927667

I had difficulty figuring out what I needed to add to set up the nightly release - IIUC the configs in https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/releases/pipeline-nightly are pulling from the repos themselves, but I only want to do a nightly release of the contents in this folder to start. Let me know if there's a way to do this, otherwise we can just stick with the the deploy-release.sh script for now.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by afrittoli** [comment]
Main releases are installed in the `dogfooding` cluster via `scripts/deploy-release.sh`.
Nightly releases are installed in the `robocat` cluster via a nightly job.
In both cases, this [template](https://github.com/tektoncd/plumbing/blob/main/tekton/resources/cd/tekton-template.yaml) is triggered, which downloads a release, applies the overlay and then deploys the result to the target cluster.

The new location of the file is ok but it won't be applied to the cluster without a `results` release, similar to what we do with 
 dashboard. 

You could setup a new cronjob to deploy this file by itself, using the folder [template](https://github.com/tektoncd/plumbing/blob/main/tekton/resources/cd/folder-template.yaml) instead, which is what we use to deploy the content of https://github.com/tektoncd/plumbing/tree/main/tekton/resources for instance. Have a look at this [job](https://github.com/tektoncd/plumbing/tree/main/tekton/cronjobs/dogfooding/manifests/plumbing-tekton) for an example.

**Pull request merged**
