### PR TITLE
Add oci labels

### PR DESCRIPTION
**Pull request by LiteBrick204**
# Changes
/kind feature

This is for #2222

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@LiteBrick204 Thank you for this PR. Could you please only include the one commit "feat: Added OCI labels for dockerfile in images folder" in this PR?
Currently it also includes a commit that belongs to https://github.com/tektoncd/plumbing/pull/2228 as well as a merge commit.

**Comment by LiteBrick204** [comment]
How do I do that?

**Comment by afrittoli** [comment]
@LiteBrick204 Sorry for the late reply, I missed your comment.
There are several ways you can do that, it depends a bit on how your local folder looks like. 
The following should work in most cases:

```
# Checkout your branch
git checkout add-oci-label

# Rename your branch
git branch -m add-oci-label-broken

# Recreate your PR branch
git checkout main
git pull
git checkout -b add-oci-label

# Cherry-pick the commit you need
GIT_SHA=$(git rev-parse add-oci-label-broken)
git cherry-pick $GIT_SHA

# If there are conflicts, solve them in the code, then 
git add -u  # only if conflicts are found
git cherry-pick --continue  # only if conflicts are found

# Finally push your branch back to the PR
# Find out the name of the remote that points to your fork ("git remote -v" if unsure)
git push <remote> add-oci-label --force
```

**Comment by LiteBrick204** [comment]
I will create a new PR since the cherry pick is failing

**Comment by LiteBrick204** [comment]
This has been pushed through #2271

**Pull request closed without merging**
