### PR TITLE
Stop using cloud events pipeline resource in CI

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Now that cloud events can be generated for any TaskRun, the setup
of Tekton based CI can be simplified.
Cloud events from CI jobs will go to the tekton-events central
event listener. With two different trigger templates the github
status is reset at the beginning of a CI job and set at the end.

The check-label job, which used its own mechanism to set the
check status on github side, now relies on the same approach used
by other CI jobs.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind cleanup

### CODE REVIEW

**Comment by afrittoli** [comment]
Rebased....

**Comment by afrittoli** [comment]
/test 
plumbing-golang-lint

**Comment by sbwsg** [comment]
/lgtm

looks like it needs a rebase tho

**Comment by afrittoli** [comment]
@sbwsg Thank you! Rebased :)

**Pull request merged**
