### PR TITLE
Continue working on unit tests for plumbing repo

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add folder with template and trigger for plumbing in the workspace-ci

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind misc
/hold

### CODE REVIEW

**Comment by afrittoli** [comment]
This works now  :)
`plumbing-unit-tests` triggers a pipeline run with a task loop inside, which runs all unit tests, one taskrun per folder in the plumbing repo!

**Review by sbwsg — APPROVED** [review]
The way the TaskLoop proxies between the pipeline and multiple sub-TaskRuns to achieve a cool scheduling behaviour is a super interesting pattern!

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
