### PR TITLE
Update cli reference to use main…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

… instead of master.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

/cc @ImJasonH @afrittoli @bobcatfish 
/cc @tektoncd/cli-maintainers 

/hold

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chmouel** [comment]
Do we have documentation for contributors on how to migrate their local repository ?

**Comment by vdemeester** [comment]
> Do we have documentation for contributors on how to migrate their local repository ?

GitHub does tell you a little something on your fork (how to rename the branch, …)

**Comment by chmouel** [comment]
Can we point it somewhere in the documentation? because i would expect a lot of repositories and maybe pipelines (i guess since it doesnt handle redirect isnt it ?) are going to fail, right?

**Pull request merged**
