### PR TITLE
Initial Prow configuration for tektoncd/cli repository

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Taken from pipeline without coverage for now (as it's a start).

/hold

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
/hold cancel

@abayer it works ! it works ! :man_dancing:

**Comment by vdemeester** [comment]
/hold
:bowing_man:

**Comment by vdemeester** [comment]
/hold cancel
I figured it out :joy_cat:

**Comment by bobcatfish** [comment]
💃

**Pull request merged**
