### PR TITLE
Fix plumbing-test-unit jobs

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

- Remove `catlin` from the list as it's not there anymore
- Add `tekton/ci/interceptors/github` as it was missing

/cc @afrittoli @dibyom @wlynch 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
An example of a unit test run : https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/plumbing-unit-tests-fwm2b?pipelineTask=unit-tests&taskRunName=plumbing-unit-tests-fwm2b-unit-tests-6&step=unit-test. 
So, the link on the github checks points to prow, which is… relatively weird… Didn't it use to link to the dashboard instead ?

**Comment by vdemeester** [comment]
So it [fails](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/plumbing-unit-tests-94895?pipelineTask=unit-tests&taskRunName=plumbing-unit-tests-94895-unit-tests-7&step=unit-test) because it is not used in the PR 😅 It needs to be deployed.

**Review by wlynch — COMMENTED** [review]
/lgtm

**Review by afrittoli — COMMENTED** [review]
/approve

**Pull request merged**
