### PR TITLE
Pin version to regular channel

### PR DESCRIPTION
**Pull request by jmcshane**
# Changes

Resolve build issues attempted in #818 and #819
by pinning version to gke-regular channel

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by jmcshane** [comment]
wait for: https://prow.tekton.dev/log?job=pull-tekton-triggers-integration-tests&id=1384598027922051073 - testing in https://github.com/tektoncd/triggers/pull/1063

**Comment by sbwsg** [comment]
I'm going to lgtm this one too as all other projects are currently blocked on it.

/lgtm

**Comment by sbwsg** [comment]
> this doesn't solve the problem long term, because at some point in the next 6 months the regular channel will be updated to 1.19.

Hopefully we can get away from the basic-auth stuff before then!

**Pull request merged**
