### PR TITLE
One more cop -> captain rename 😌

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

Hopefully the last one? Not sure how I missed it before!

I'm going for the many tiny PR award today 🏆 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
@bobcatfish do we need to change where we refer the configmap or did it change already ?
/test .*

**Comment by bobcatfish** [comment]
@vdemeester ive made the change in https://github.com/tektoncd/plumbing/pull/672 and i manually made the change in the cluster (some details in https://github.com/tektoncd/plumbing/pull/672#issuecomment-767090532) - tho currently we have BOTH config maps, prolly makes sense to delete the old one some day :D

**Pull request merged**
