### PR TITLE
Update infra monitoring role name to buildcaptain

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

We recently surveyed folks on their preferred name for the infra
monitoring rotation we run to keep an eye on our nightlies and
PR infra. "BuildCaptain" won the day.

Updating as many references as I can find here. I haven't updated the deployment yet, just the
buildbot code.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by sbwsg** [comment]
The tests pass locally for me, though I did have to run with `CGO_ENABLED=0` otherwise it errored out because `clang` isn't on my PATH.

**Review by vdemeester — APPROVED** [review]
/cc @bobcatfish

**Comment by bobcatfish** [comment]
Thanks for taking this on @sbwsg !!! ❤️

**Pull request merged**
