### PR TITLE
Adapt tekton resources for triggers v11

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Template name is not supported anymore.
Handling of body extensions through interceptors and overlays is
a different, change event listeners and bindings to reflect that.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind misc

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @dibyom @sbwsg @savitaashture

**Comment by afrittoli** [comment]
/hold until https://github.com/tektoncd/triggers/pull/912 is merged
Would be good to have https://github.com/tektoncd/plumbing/pull/683 too

With the trigger patch in a deployed to robocat I can then fix the template name -> ref on robocat and restore the ability to deploy to dogfooding. We can then start the following plan:

1. merge this PR
2. delete all event listeners
3. update triggers on dogfooding
4. let event listeners be re-created by the automatic deployment
5. redeploy the custom interceptors from master
6. update pipeline and dashboard

**Comment by dibyom** [comment]
Once tektoncd/triggers#912 is merged, do we still need to delete/recreate all EventListeners?

**Comment by savitaashture** [comment]
> Once [tektoncd/triggers#912](https://github.com/tektoncd/triggers/pull/912) is merged, do we still need to delete/recreate all EventListeners?

I think its not required to delete/recreate eventlistener

**Comment by afrittoli** [comment]
> > Once [tektoncd/triggers#912](https://github.com/tektoncd/triggers/pull/912) is merged, do we still need to delete/recreate all EventListeners?
> 
> I think its not required to delete/recreate eventlistener

We don't need to anymore, thank you for your help with the patch release!

**Pull request merged**
