### PR TITLE
[github-simple] Move resources to tekton-ci namespace.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

This moves the github-simple interceptor into the same namespace as the
add-pr-body and add-team-members interceptors. This namespace also
contains the ci-webhook secret, which is the webhook secret used in
dogfooding.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @afrittoli

**Comment by afrittoli** [comment]
Oh, I think the `check-pr-has-kind-label` job may have been broken by the changes in workDir and HOME.
I'll prepare a fix.

**Pull request merged**
