### PR TITLE
Add conformance tests to presubmit-tests.sh

### PR DESCRIPTION
**Pull request by yaoxiaoqi**
# Changes

Conformance tests are used to check API specs of different implementation Tekton. This PR adds conformance tests to presubmit-tests.sh and updates the related content in scripts/README.md.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by ImJasonH — COMMENTED** [review]
/lgtm

**Review by vdemeester — APPROVED** [review]
/meow

**Pull request merged**
