### PR TITLE
Fix pull-tekton-experimental-helm-lint

### PR DESCRIPTION
**Pull request by eddycharly**
Added missing entrypoint.

It should be ok now, sorry for the inconvenience, it's not easy to get the job definition right first try.

### CODE REVIEW

**Comment by bobcatfish** [comment]
@eddycharly and @vdemeester is this part of a larger effort, e.g. an issue? it'd be really useful to be able to trace back the history of these changes if we needed to later

(e.g. an issue that describes what we're trying to do, referenced in each of these PRs, perhaps the commit messages as well)

**Comment by eddycharly** [comment]
Working towards #306.

@bobcatfish i created the issue, linking it in the PRs for history.

**Comment by bobcatfish** [comment]
Perfect!! Thanks @eddycharly I appreciate it! :D

**Pull request merged**
