### PR TITLE
Fix description field on tasks

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

`description` should be set as `spec.description`, NOT as `metadata.description`.

This is preventing a number of jobs from running successfully, e.g. https://dashboard.dogfooding.tekton.dev/#/namespaces/default/pipelineruns/deploy-resources-tekton-sgmwh?pipelineTask=deploy&step=deploy-from-folder

```
Error from server (BadRequest): error when creating "target.yaml": Task in version "v1beta1" cannot be handled as a Task: strict decoding error: unknown field "metadata.description"
Error from server (BadRequest): error when creating "target.yaml": Task in version "v1beta1" cannot be handled as a Task: strict decoding error: unknown field "metadata.description"
+ echo 'Something went wrong when creating resources'
+ exit 1
Something went wrong when creating resources
```
/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
Failing on unrelated changes: https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/plumbing-unit-tests-nmkks?pipelineTask=unit-tests&taskRunName=plumbing-unit-tests-nmkks-unit-tests-2

- `catlin` was removed from the list of tests in https://github.com/tektoncd/plumbing/pull/1766 but is still being run

- `pipelinerun-logs`:
  ```
  2024-02-20T11:21:11.970206551Z /go/pkg/mod/go.opentelemetry.io/otel@v1.22.0/internal/global/handler.go:44:18: undefined: atomic.Pointer
  2024-02-20T11:21:11.970213260Z /go/pkg/mod/go.opentelemetry.io/otel@v1.22.0/internal/global/internal_logging.go:30:25: undefined: atomic.Pointer
  2024-02-20T11:21:11.970219332Z note: module requires Go 1.20
  2024-02-20T11:21:17.726764751Z # [google.golang.org/grpc](http://google.golang.org/grpc)
  2024-02-20T11:21:17.726811555Z /go/pkg/mod/google.golang.org/grpc@v1.61.0/server.go:2182:14: undefined: atomic.Int64
  2024-02-20T11:21:17.726819287Z note: module requires Go 1.19
  2024-02-20T11:21:22.956548163Z FAIL	[github.com/tektoncd/plumbing/pipelinerun-logs/cmd/http](http://github.com/tektoncd/plumbing/pipelinerun-logs/cmd/http) [build failed]
  ```
- `tekton/ci/custom-tasks/pr-commenter` looks similar to `pipelinerun-logs` issue:
  ```
  2024-02-20T11:22:45.279560723Z /go/pkg/mod/google.golang.org/grpc@v1.60.1/server.go:2165:14: undefined: atomic.Int64
  2024-02-20T11:22:45.279570778Z note: module requires Go 1.19
  2024-02-20T11:22:49.035353543Z # go.uber.org/multierr
  2024-02-20T11:22:49.035394267Z /go/pkg/mod/go.uber.org/multierr@v1.10.0/error.go:224:20: undefined: atomic.Bool
  2024-02-20T11:22:49.035401565Z note: module requires Go 1.19
  2024-02-20T11:23:01.870380026Z # k8s.io/client-go/tools/cache/synctrack
  2024-02-20T11:23:01.870435897Z /go/pkg/mod/k8s.io/client-go@v0.29.1/tools/cache/synctrack/lazy.go:29:15: undefined: atomic.Pointer
  2024-02-20T11:23:01.870445620Z note: module requires Go 1.21
  2024-02-20T11:24:00.510388015Z # k8s.io/kube-openapi/pkg/cached
  2024-02-20T11:24:00.510440045Z /go/pkg/mod/k8s.io/kube-openapi@v0.0.0-20231010175941-2dd684a91f00/pkg/cached/cache.go:258:15: undefined: atomic.Pointer
  2024-02-20T11:24:00.510447326Z /go/pkg/mod/k8s.io/kube-openapi@v0.0.0-20231010175941-2dd684a91f00/pkg/cached/cache.go:270:17: undefined: atomic.Pointer
  2024-02-20T11:24:00.510452835Z note: module requires Go 1.19
  2024-02-20T11:24:32.693639478Z FAIL github.com/tektoncd/plumbing/tekton/ci/custom-tasks/pr-commenter/pkg/reconciler [build failed]
  ```
- `tekton/ci/custom-tasks/pr-status-updater` same

**Comment by vdemeester** [comment]
@AlanGreene is it a follow-up of https://github.com/tektoncd/plumbing/pull/1834 ?

**Comment by vdemeester** [comment]
oh wait, I am lost now 😂

**Pull request closed without merging**
