### PR TITLE
Correct the pipeline version for PROW integration.

### PR DESCRIPTION
**Pull request by gyliu513**
# Changes

Fixed https://github.com/tektoncd/plumbing/issues/546

/cc @eddycharly @vdemeester 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by gyliu513** [comment]
I signed the CLA just now.

**Review by vdemeester — APPROVED** [review]
/meow
/cc @bobcatfish @afrittoli @sbwsg

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
