### PR TITLE
Enable minimal embedded status is alpha integration tests

### PR DESCRIPTION
**Pull request by jerop**
# Changes

In https://github.com/tektoncd/pipeline/pull/5032, we added the logic for setting embedded status when running end to end tests.

In this change, we set `embedded-status` to `"minimal"` so that we can dogfood the feature alongside other alpha features. This also allows us to run examples with `Matrix` which needs minimal embedded status.

As discussed in slack thread: https://tektoncd.slack.com/archives/CJ4ERJWAU/p1655990546574359

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by jerop** [comment]
cc @abayer @afrittoli @dibyom

**Review by afrittoli — COMMENTED** [review]
/approve

**Pull request merged**
