### PR TITLE
Update stockout message check in e2e-test.sh

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

This error message has changed over time, so the previous check is no
longer working. Long term we may want to consider moving to an actual
client so that we can check the status enum being returned in the
response.

/bug cleanup

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @afrittoli

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
