### PR TITLE
Add template and triggers for gubernator logs

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add templates and triggers to run pipelines that store logs
and metadata for gubernator on GCS buckets.

The target for now is set to a staging bucket for testing
purposes.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind feature

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
Depends-on https://github.com/tektoncd/catalog/pull/964

**Comment by afrittoli** [comment]
With the new version of the gcs-upload task, it takes now <1min:

- [start](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/4e1cfc70-b5c5-plumbing-yamllint-logs-start?pipelineTask=create-data&step=write-data)
- [stop](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/4e1cfc70-b5c5-plumbing-yamllint-logs-stop?pipelineTask=create-data&step=write-data)

This doesn't seem to work with gubernator out of the box, because it expects numeric build numbers (instead of the alphanumeric pipeline run used here), but it provides at least a permanent storage for build logs.

Next step could be to log a link to the dashboard, and set the link in the github status to the log in GCS directly. That way users will have a permanent log to look at, and they will be able to check the dashboard as long as the PR is not pruned.

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
