### PR TITLE
Bump ko to v0.7.0 on CI and release images

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This will allow us to use `--platform=linux/amd64,linux/arm64` (aka multiple architecture with `--platform`)

/cc @afrittoli 

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
Thanks! 
/approve

**Review by afrittoli — COMMENTED** [review]
Nice, make sense.
/approve

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
