### PR TITLE
Add python3 to the image 😛

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

And install yamllint using python3 instead of python 2.7

/cc @afrittoli @chmouel @danielhelfand 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

thanks 🙇

**Comment by afrittoli** [comment]
luigi at your service! </p>Here is the image you requested: <a href="http://gcr.io/tekton-releases/dogfooding/test-runner:mario">built image</a>|<a href="http://35.222.249.224/?buildid=a6c39ec4-af26-4040-be6b-fa0ccb506473&namespace=mario">build logs</a>

**Comment by vdemeester** [comment]
Might be taken over by https://github.com/tektoncd/plumbing/pull/295 :stuck_out_tongue:

**Comment by sbwsg** [comment]
/approve

Those darn python2 yamllint errors!  :shakes fist at cloud:

**Pull request merged**
