### PR TITLE
Add Makefile for Catlin

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

Add a Makefile for catlin with a few common targets.
Add the vendor directory too.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
I wonder if we want to add `vendor` though. So far we didn't rely on `vendor` for any go tooling in that repository to not have a huge content (like multiple vendor directory for each go tool). @chmouel Could we split the `Makefile` from the vendor part to get one in quickly and discuss the other ?

**Comment by chmouel** [comment]
either way to not adding it i am fine... i just followed what we had in other tekton repository.

**Comment by bobcatfish** [comment]
@chmouel is this the kind of thing we'd want to have in our Pipelines and Tasks? i'm wondering why we'd want to use a makefile for this vs having using a go build Task

**Comment by chmouel** [comment]
@bobcatfish it's only there to be able run the test or linter easily when developing on the local developer machine, I don't think we have a solution for that

**Comment by bobcatfish** [comment]
ah okay, interesting, thanks @chmouel

i hope one day we'll make it so we don't have to have a different set of scripts and automation for local development (https://github.com/tektoncd/community/issues/145 🤞 )

**Comment by chmouel** [comment]
I think the yamllint job has some issues i have logged an issue here : 

https://github.com/tektoncd/plumbing/issues/698

**Review by afrittoli — COMMENTED** [review]
/approve

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
