### PR TITLE
Add docker-in-docker image to fix Ci issue in s390x dogfooding cluster

### PR DESCRIPTION
**Pull request by Basavaraju-G**
# Changes
Add docker-in-docker image in sidecar to address recent changes in dashboard repo. [PR](https://github.com/tektoncd/dashboard/pull/2439)
Set SKIP_INITIALIZE variable to skip cluster creation.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by Basavaraju-G** [comment]
@jerop @dlorenc would you please review this PR?

**Review by afrittoli — COMMENTED** [review]
Thank you
/approve

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
