### PR TITLE
Fix Tekton GitHub org name in scripts/library.sh

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Replaces "github.com/tekton/" with "github.com/tektoncd/"

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
what happened to the cat plugin!

**Comment by bobcatfish** [comment]
weeeird

**Comment by vdemeester** [comment]
@bobcatfish it's the third time in a row it refuse my command :sweat_smile: :bowing_man:

**Pull request merged**
