### PR TITLE
Pin verison of ko we install 📌

### LINKED ISSUE #370: ko failing to publish nightly image
pipeline-release-nightly-w9cjw failed in the dogfood cluster last night, specifically pipeline-release-nightly-w9cjw-publish-images-krlpp failed with:

```
[run-ko] 2020/05/04 02:09:24 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/kubeconfigwriter
[run-ko] 2020/05/04 02:09:26 Building github.com/tektoncd/pipeline/vendor/github.com/GoogleCloudPlatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher
[run-ko] 2020/05/04 02:09:26 Building github.com/tektoncd/pipeline/cmd/kubeconfigwriter
[run-ko] 2020/05/04 02:09:34 Using base gcr.io/distroless/static:latest for github.com/tektoncd/pipeline/cmd/imagedigestexporter
[run-ko] 2020/05/04 02:09:34 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 02:09:34 Unexpected error running "go build": signal: killed
[run-ko] 2020/05/04 02:09:35 Building github.com/tektoncd/pipeline/cmd/imagedigestexporter
[run-ko] 2020/05/04 02:09:35 Unexpected error running "go build": context canceled
[run-ko] 2020/05/04 02:09:35 error processing import paths in "/workspace/go/src/github.com/tektoncd/pipeline/config/webhook.yaml": error resolving image references: repository can only contain the runes `abcdefghijklmnopqrstuvwxyz0123456789_-./`: tekton-nightly/ko://github.com/tektoncd/pipeline/cmd/webhook

```

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

We were installing ko from master @ head which means if any bugs are
introduced, we'll hit them. A bug was introduced in how -P works which
was fixed in https://github.com/google/ko/pull/163 by @mattmoor almost
immediately so let's pin to the version with that fix so we can deal
with changes to ko at our leisure vs. surfacing ko errors in our CI.

Fixes #370

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
@bobcatfish I think you need to rebase against latest upstream master to remove the error :angel:

**Comment by bobcatfish** [comment]
plumbing-ko-build seems to have this failure:

```
{"level":"error","ts":1588690523.1534953,"caller":"git/git.go:41","msg":"Error running git [fetch --recurse-submodules=yes --depth=2 origin e0e4fdaa58212693ee38ffe3d94c140b0162f1c9]: exit status 128\nfatal: unable to access 'https://github.com/tektoncd/plumbing/': Failed to connect to github.com port 443: Operation timed 
```

**Comment by bobcatfish** [comment]
Not sure how to re-trigger the check, maybe thats a WIP ( @afrittoli lemme know if there's a way ) I'll just force push a commit message change to trigger again

**Comment by sbwsg** [comment]
/lgtm

:shipit:

**Pull request merged**
