### PR TITLE
Fix kind-e2e image by upgrading base image to Go 1.17.x

### PR DESCRIPTION
**Pull request by abayer**
# Changes

And while I'm here, update a number of other images.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by afrittoli — APPROVED** [review]
/lgtm

**Comment by abayer** [comment]
ah, ha, my switch to `go install` broke stuff!

**Comment by afrittoli** [comment]
> Ok, `plumbing-image-build` claims it failed, but every step passed...I am confused.

Something is wrong with the task-loop custom tasks + github notification, I think.
It seems to be racy so let me give it another try

**Comment by abayer** [comment]
/hold

The `plumbing-image-build` marks itself as passed too quickly. =)

**Comment by abayer** [comment]
/hold cancel

...and `plumbing-yamllint` is back thinking it hasn't finished when it in fact has.

**Pull request merged**
