### PR TITLE
Remove build cops during christmas break 🎅

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Because, we all need to rest and take care of our familly and friend 😉

oh oh oh

/cc @bobcatfish @afrittoli @abayer 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
Yay!!
/lgtm

**Comment by bobcatfish** [comment]
well that cat picture is definitely > #172  XD

(@vdemeester @afrittoli what do you think about including plumbing in our build cop rotation?)

**Comment by bobcatfish** [comment]
:massage_woman:

**Pull request merged**
