### PR TITLE
WIP: Deploy/configure Pipeline remote resolvers in dogfooding and robocat

### PR DESCRIPTION
**Pull request by abayer**
# Changes

Need to hold off on this until we're ready to upgrade to v0.40.0.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by abayer** [comment]
(I'm testing to see if the PR commenter is working)

**Comment by abayer** [comment]
Ah, it hasn't deployed yet?

**Comment by afrittoli** [comment]
@abayer I believe this can be closed now. v0.41.0 is deployed on dogfooding and resolvers are part of the release there.

**Pull request closed without merging**
