### PR TITLE
Enables cherry-pick plugin in prow for tektoncd/operator

### PR DESCRIPTION
**Pull request by sm43**
we would like to enable the cherrypicker plugin in prow for operator repository
https://github.com/kubernetes/test-infra/tree/master/prow/external-plugins/cherrypicker

eg.
```
/cherrypick release-1.10
```

following the docs at https://github.com/kubernetes/test-infra/blob/master/prow/plugins/README.md#external-plugins
enabling the cherrypicker external plugin for operator repository

Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by sm43** [comment]
/cc @vdemeester @afrittoli 
let me know what do you think?

**Review by vdemeester — APPROVED** [review]
I think it make sense 👍🏼 
As is, it enables it only on `tektoncd/operator` right ? If yes, we can start like this and slowly move towards enabling on other repositories as well.

**Comment by abayer** [comment]
/lgtm

Sounds worth trying out!

**Pull request merged**
