### PR TITLE
Add the "kind label" check into the CI event listener

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

We already have an event listener behind an ingress, so add the
"kind label" check into it. Check check should be quick enough
that it doesn't need the reset status / set status like other CI
jobs.

Do not add any repo filter for now, until we experiment on plumbing.
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
/hold

I got the `TaskRun` to trigger the check, however it the pod fails to mount the configmap - which makes sense since the configmap is in a different cluster (`prow`).
I see two options forward:
- deploy the same configmap in the `dogfooding` cluster too
- hardcode a list of labels that we want in the job 

@vdemeester thoughts?

**Comment by vdemeester** [comment]
> /hold
> 
> I got the `TaskRun` to trigger the check, however it the pod fails to mount the configmap - which makes sense since the configmap is in a different cluster (`prow`).
> I see two options forward:
> 
>     * deploy the same configmap in the `dogfooding` cluster too
> 
>     * hardcode a list of labels that we want in the job
> 
> 
> @vdemeester thoughts?

I would go for deploying the same configmap in the `dogfooding` cluster :wink:

**Comment by afrittoli** [comment]
> **This PR cannot be merged:** expecting exactly one kind/ label
> 
> Available `kind/` labels are:
> 
> `kind/bug`: Categorizes issue or PR as related to a bug.
> `kind/flake`: Categorizes issue or PR as related to a flakey test
> `kind/cleanup`: Categorizes issue or PR as related to cleaning up code, process, or technical debt.
> `kind/design`: Categorizes issue or PR as related to design.
> `kind/documentation`: Categorizes issue or PR as related to documentation.
> `kind/feature`: Categorizes issue or PR as related to a new feature.
> `kind/misc`: Categorizes issue or PR as a miscellaneuous one.

@tomgeorge  🎉

**Pull request merged**
