### PR TITLE
Catlin: Adds README

### PR DESCRIPTION
**Pull request by SM43**
Signed-off-by: Shivam Mukhade <smukhade@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

cc @sthaha  @vdemeester

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow

**Review by sthaha — COMMENTED** [review]
/lgtm
/approve
/meow

**Pull request merged**
