### PR TITLE
Pin ko to 0.5.1 in test-runner and ko

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Follow up on #427

This should hopefully fix the nightly too (they might use `ko` 0.5.0 with this patch).

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
We should be able to merge https://github.com/tektoncd/pipeline/pull/2675 and see if the nightly are still failing or not.

**Comment by bobcatfish** [comment]
I honestly think that even when you pin this, go get doesn't always use the commit associated with the tag, I really don't understand it - let's give it a shot anyway tho!

/approve
/lgtm

**Comment by bobcatfish** [comment]
Triggered new image builds with:

```
k --context dogfood create job --from cronjob/image-build-cron-trigger-ko image-build-cron-trigger-ko-manual-07062020

k --context dogfood create job --from cronjob/image-build-cron-trigger-ko-gcloud image-build-cron-trigger-ko-gcloud-manual-07062020

k --context dogfood create job --from cronjob/image-build-cron-trigger-test-runner image-build-cron-trigger-test-runner-manual-07062020
```

**Pull request merged**
