### PR TITLE
Update tkn to v0.13.0

### PR DESCRIPTION
**Pull request by danielhelfand**
Updating test-runner/tkn image to [tkn v0.13.0](https://github.com/tektoncd/cli/releases/tag/v0.13.0). 

# Submitter Checklist

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
