### PR TITLE
Add missing tetkon-cd-template

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

PR https://github.com/tektoncd/plumbing/pull/513 added a reference
to the tekton-cd-template but failed to include the file, which
is causing the resource deployment to fail.

Adding the file back and fixing the template used for the `all`
triggers.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind bug

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by afrittoli** [comment]
> /test check-pr-has-kind-label

It works!

**Pull request merged**
