### PR TITLE
Configure the git resolver with the GitHub API token

### PR DESCRIPTION
**Pull request by abayer**
# Changes

I'm not 100% sure if this is right - specifically, this is trying to write to the `git-resolver-config` `ConfigMap` in the `tekton-pipelines-resolvers` namespace, but I put it in the same directory as the rest of the pipelines overlays. @afrittoli - I _think_ this should work correctly, but I defer to you. =)

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by lbernick** [comment]
@abayer is there a way to test this/have you tested this? (maybe at least build w/ kustomize and see what the diff is compared to the dogfooding cluster?)

**Review by afrittoli — COMMENTED** [review]
I think you'll have to update https://github.com/tektoncd/plumbing/blob/main/tekton/cd/pipeline/overlays/dogfooding/kustomization.yaml as well

**Comment by abayer** [comment]
> @abayer is there a way to test this/have you tested this? (maybe at least build w/ kustomize and see what the diff is compared to the dogfooding cluster?)

I'm asking @afrittoli about this in the productivity WG in a few minutes. =)

**Comment by abayer** [comment]
kustomization has now been updated!

**Comment by abayer** [comment]
And I've verified (after copying https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.44.0/release.yaml into `tekton/cd/pipeline/base`) that the output of `kubectl kustomize tekton/cd/pipeline/overlays/dogfooding` does contain the expected `git-resolver-config` configmap, so yeah, this is good to merge.

**Review by jerop — APPROVED** [review]
thanks @abayer

**Pull request merged**
