### PR TITLE
Update dashboard reference to use main…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

… instead of master.

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

/cc @ImJasonH @afrittoli @bobcatfish 
/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by ImJasonH — COMMENTED** [review]
/lgtm

**Review by afrittoli — COMMENTED** [review]
/hold

**Comment by AlanGreene** [comment]
Thanks @vdemeester
/lgtm

**Comment by vdemeester** [comment]
/hold cancel
Renamed already 😛

**Pull request merged**
