### PR TITLE
Add a python unit tests job to the website

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add a python unit test job to the website, which uses the pytest
task from the catalog. This will run unit tests for the sync and
versions python tools.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind feature

### CODE REVIEW

**Comment by afrittoli** [comment]
Example run: https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/pull-website-python-unit-6k8wf?pipelineTask=unit-tests

On this PR: https://github.com/tektoncd/website/pull/325

/cc @vdemeester

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
