### PR TITLE
Add tektoncd-catalog org under Prow

### PR DESCRIPTION
**Pull request by QuanZhang-William**
This commit adds `tektoncd-catalog` org to `prow/config.yaml` and `prow/plugins.yaml` files. It applies the same configuration to `tektoncd-catalog` as `tektoncd` org to achieve the same level of automation and administration.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by QuanZhang-William** [comment]
@vdemeester @dibyom @abayer @afrittoli. Could you please help check if there is anything missing in the setup? I'm not sure if I can test these changes locally. 🤔 

2 Related PR: 
https://github.com/tektoncd/plumbing/pull/1318
https://github.com/tektoncd/community/pull/933

**Review by dibyom — COMMENTED** [review]
This looks good to me - do you want to coordinate on when to merge this so that we could roll it back quickly in case something breaks?

**Review by vinamra28 — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
