### PR TITLE
prow: using presets to remove duplicates in jobs…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This defines 3 presets that can be used using labels on job
definitions:
- `"preset-presubmit-sh": "true"` for common presubmit jobs
- `"preset-postsubmit-sh": "true"` for common postsubmit jobs
- `"preset-github-token": "true"` for jobs that needs a github-token

Preset documentation is available here: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#presets.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli @nikhil-thomas @bobcatfish 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
@afrittoli @nikhil-thomas @bobcatfish @sbwsg do you think this change make sense ?

**Comment by afrittoli** [comment]
> @afrittoli @nikhil-thomas @bobcatfish @sbwsg do you think this change make sense ?

I think it does. 
I'm not sure how to verify that it doesn't break anything... do you have a cluster where to test it?

**Comment by sbwsg** [comment]
This makes sense to me, less lines = big improvement.

The only part that confused me was the uncommenting of `pull-tekton-dashboard-integration-0-11-3-tests`. Is that related to these presets somehow?

**Comment by bobcatfish** [comment]
I haven't looked at the changes line by line but makes sense to me in theory!

**Comment by vdemeester** [comment]
> This makes sense to me, less lines = big improvement.
> 
> The only part that confused me was the uncommenting of `pull-tekton-dashboard-integration-0-11-3-tests`. Is that related to these presets somehow?

Oh, good point, I missed removing that part from my diff on rebase..

**Comment by sbwsg** [comment]
cool, am happy to lgtm but one more question - i'm not sure if `pull-tekton-pipeline-integration-auth-webhook-tests` is new or i missed it on my first review.  also related to these changes?

**Comment by vdemeester** [comment]
> cool, am happy to lgtm but one more question - i'm not sure if `pull-tekton-pipeline-integration-auth-webhook-tests` is new or i missed it on my first review. also related to these changes?

lol, you are seeing all the thing I miss :heart_eyes_cat:

**Review by afrittoli — COMMENTED** [review]
Thanks for this!
/lgtm

**Pull request merged**
