### PR TITLE
Try to find team key in the right place of the payload

### PR DESCRIPTION
**Pull request by fiunchinho**
/kind bug

# Changes

When I did the change I didn't take into consideration the new place (`extensions`) where some fields are placed now.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
Thank you :rocket:

**Comment by fiunchinho** [comment]
is there anything else you need so we can merge this? thanks!

**Review by afrittoli — COMMENTED** [review]
Thank you!
/approve
/lgtm

**Pull request merged**
