### PR TITLE
Update trigger template params to use tt.params

### PR DESCRIPTION
**Pull request by savitaashture**
# Changes

Closes https://github.com/tektoncd/plumbing/issues/491

/cc @afrittoli 

Signed-off-by: Savita Ashture sashture@redhat.com

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by dibyom** [comment]
I think with this change, you should be able to upgrade to v0.7 when it comes out next week

**Comment by afrittoli** [comment]
CI seems to be working still fine after the update of triggers to v0.6.1 🎉 
/approve

**Pull request merged**
