### PR TITLE
OWNERS: update based on buildcops 🙃

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

It also adds additional timezone covered.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli @bobcatfish @sbwsg @jerop @nikhil-thomas @savitaashture @abayer @wlynch 

(@abayer please tell me if you still want to be an OWNER of plumbing or not :stuck_out_tongue: :upside_down_face: )

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by savitaashture** [comment]
/lgtm

Thank you :slightly_smiling_face:

**Comment by abayer** [comment]
I'm fine either way, honestly. =)

**Comment by bobcatfish** [comment]
@vdemeester would it make sense to update the owner requirements: https://github.com/tektoncd/plumbing/blob/master/CONTRIBUTING.md#contributing-to-the-plumbing-repo

**Comment by vdemeester** [comment]
> @vdemeester would it make sense to update the owner requirements: https://github.com/tektoncd/plumbing/blob/master/CONTRIBUTING.md#contributing-to-the-plumbing-repo

So you could be an OWNER without being a buildcop, but I think you should be an OWNER if you are a buildcop (that way you can fix things more easily). So yeah, we may want to update `CONTRIBUTING.md` :upside_down_face:

**Pull request merged**
