### PR TITLE
Always make sure module cache is downloaded.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

This ensures that `go mod download` in tests/scripts to make sure all
dependencies are present. This should generally only be slow on the first
attempt when it needs to download the modules locally, but subsequent calls
should result in no change.

This solves an issue raised in
https://github.com/tektoncd/pipeline/pull/1792 where the license DB used
by a required tool wasn't being downloaded.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
ping @wlynch  - still worth doing this or should we close for now?

**Comment by sbwsg** [comment]
Following up here, @wlynch wdyt about closing this for now and revisiting at a later time?

**Comment by vdemeester** [comment]
Agreeing with @bobcatfish and @sbwsg, let's close this for now :wink:
/close

**Pull request closed without merging**
