### PR TITLE
Add example testsuite for tekton-pipeline CI job for ppc64le

### PR DESCRIPTION
**Pull request by Sachin-Itagi**
This PR adds the previously missing example-test in the tekton-pipeline CI job for ppc64le
# Changes
Added the previously missing example-test-pipeline for the tekton-pipeline CI job.

Additionally have hard coded the value for container registry with an insecure local registry to fix pipelines CI failure due to push permission error as mentioned in this PR #1399 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
cc @afrittoli

**Comment by Sachin-Itagi** [comment]
@vdemeester @khrm @afrittoli Can we proceed with merging the PR if everything seems fine. The Checks seem to have passed.

**Comment by vdemeester** [comment]
Something is weird with the tekton based CI 🤔

**Review by vdemeester — APPROVED** [review]
cc @afrittoli

**Comment by Sachin-Itagi** [comment]
@vdemeester @afrittoli Any update on this PR.

**Comment by Sachin-Itagi** [comment]
@afrittoli @dibyom Please review this PR.

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
