### PR TITLE
Update Go to 1.20.10

### PR DESCRIPTION
**Pull request by khrm**
Needed for CVE fix: https://github.com/golang/go/issues/63426

Triggers EventListener, Hub, and Results are affected.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind security

**Comment by vdemeester** [comment]
/approve

@khrm this is needed for more than just this image. I am ok merging this to quickly allow release pipeline that use this image to benefit from it, but we need to upgrade all golang usage.

**Comment by khrm** [comment]
@vdemeester This isn't merged. I think upstream releases still have HTTP2 CVE then.

**Comment by vdemeester** [comment]
/lgtm

Let's get this one merged and I'll follow-up

**Pull request merged**
