### PR TITLE
Fix args for testgrid setup and make non blocking

### PR DESCRIPTION
**Pull request by lbernick**
GCS buckets are prefixed by "gs" not "gcs".

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- n/a Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by dibyom — APPROVED** [review]
/lgtm

**Review by dibyom — APPROVED** [review]
/lgtm

**Comment by lbernick** [comment]
/override pull-tekton-plumbing-check-testgrid-config

making this optional until we get it working, but changes here won't be reflected until this PR is submitted

**Comment by dibyom** [comment]
I manually merged this since this was breaking Prow config.
Temporarily disabled status check, rebase + merge, and re-enabled status check.

**Pull request merged**
