### PR TITLE
Bump test-runner to golang 1.21

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Bump test-runner to golang 1.21

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vinamra28** [comment]
@wlynch, can we close this in favour of https://github.com/tektoncd/plumbing/pull/1854 ?

**Comment by wlynch** [comment]
Fine with closing this, but we should try to merge https://github.com/tektoncd/plumbing/pull/1848 instead - it's blocking chains

**Comment by vdemeester** [comment]
oh

**Pull request closed without merging**
