### PR TITLE
Add support to mount another secret "e2e-secret" into integration tests.

### PR DESCRIPTION
**Pull request by dlorenc**
# Changes

This secret will contain credentials used to access APIs required in tests.
Examples include:
- github/gitlab tokens for the PR resource
- registry tokens
- more!

We should still strive to make tests hermetic where possible, but test coverage
with secrets and service dependencies is better than no coverage.

See https://github.com/tektoncd/pipeline/pull/1557 for the other half of how this
will be used.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
Can has doc update also? :memo:

**Comment by bobcatfish** [comment]
ping @dlorenc

**Comment by afrittoli** [comment]
> ping @dlorenc

re-ping? @dlorenc

**Comment by sbwsg** [comment]
I'm going to close this for now.  Please feel free to reopen and respond if the feature is still desirable!

/close

**Pull request closed without merging**
