### PR TITLE
Setup e2e tests on kind

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add a kind-e2e container image with an embedded setup-kind script.
The kind-e2e image includes libraries need to run E2E tests.
Add a cronjob to build the image nightly.

Add a task which runs dind in a sidecar and which triggers
the setup-kind and can run a script on top of the kind cluster.

Setup a generic pipeline which clones a repo and runs the kind
tasks. The repo is used to source the test job.

Add a CI job the pipeline repo that uses the e2e-kind pipeline.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind feature

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
Added docs in the last revision.

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
