### PR TITLE
Fix the migrated yamllint job

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

A couple of issues were introduced in the yamllint job in the process
of migrating it from ci to ci-workspace, whicha are fixed here.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind misc

### CODE REVIEW

**Comment by afrittoli** [comment]
@vdemeester First batch of fixes after https://github.com/tektoncd/plumbing/pull/953 - yamlint job is fixed - fixed version running on this PR.

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
@tektoncd/plumbing-maintainers looking for an lgtm on this 🙏

**Pull request merged**
