### PR TITLE
prow: fix tektoncd/cli 0_10 integration job

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

I accidently removed the environment variable when migrating the
configuration to presets…

Fixes tektoncd/cli#1193

/cc @nikhil-thomas @afrittoli @savitaashture @danielhelfand 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by savitaashture — APPROVED** [review]

**Review by piyush-garg — APPROVED** [review]
/lgtm

**Pull request merged**
