### PR TITLE
Add the openssh-server cronjob to kustomize

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add the cronjob to kustomize so it gets deployed.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind bug

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by afrittoli** [comment]
Yaml lint status pending:
https://dashboard.dogfooding.tekton.dev/#/namespaces/tektonci/taskruns/plumbing-yamllint-pr-pending-j7j8n?step=update-check-status

```
[pr-source-pr-z8q5b] {"level":"info","ts":1600771711.2977893,"caller":"pullrequest-init/main.go:57","msg":"RUNNING DOWNLOAD!","resource_type":"pullrequest","mode":"download"}
[pr-source-pr-z8q5b] {"level":"info","ts":1600771711.2978637,"caller":"pullrequest/api.go:54","msg":"finding pr","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-z8q5b] {"level":"info","ts":1600771711.697027,"caller":"pullrequest/api.go:61","msg":"finding combined status","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-z8q5b] {"level":"info","ts":1600771711.7935426,"caller":"pullrequest/api.go:72","msg":"finding comments: %v&{0xc0000c6b40 tektoncd/plumbing 588 0xc0000b6570}","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-z8q5b] {"level":"info","ts":1600771711.9074035,"caller":"pullrequest/api.go:77","msg":"found comments: %v[0xc000310000]","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}


[update-check-status] New status: {'State': 'pending', 'Label': 'plumbing-yamllint', 'Desc': 'Job Triggered.', 'Target': 'https://dashboard.dogfooding.tekton.dev/#/namespaces/tektonci/pipelineruns/tekton-yamllint-q64xj?pipelineTask=lint'}

[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.1492696,"caller":"pullrequest-init/main.go:68","msg":"RUNNING UPLOAD!","resource_type":"pullrequest","mode":"upload"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.151727,"caller":"pullrequest/api.go:114","msg":"Syncing resource: &{PR:0xc000140000 Statuses:[0xc0001f2180 0xc0001f21c0 0xc0001f2200 0xc0001f2240 0xc0001f2280] Comments:[0xc0001301c0] Manifests:map[comments:map[696644952:true] labels:map[approved:true kind%2Fbug:true lgtm:true size%2FXS:true]]}","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.3814518,"caller":"pullrequest/api.go:285","msg":"Looking for existing status on 016d843048266c6400dc4d81b57c256e035e2b51","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.478358,"caller":"pullrequest/api.go:301","msg":"Skipping setting EasyCLA because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.4784176,"caller":"pullrequest/api.go:301","msg":"Skipping setting check-pr-has-kind-label because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.478432,"caller":"pullrequest/api.go:301","msg":"Skipping setting plumbing-golang-lint because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.4784443,"caller":"pullrequest/api.go:311","msg":"Creating status plumbing-yamllint on 016d843048266c6400dc4d81b57c256e035e2b51","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.7572317,"caller":"pullrequest/api.go:301","msg":"Skipping setting tide because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-lcmbm] {"level":"info","ts":1600771714.7577426,"caller":"pullrequest/api.go:184","msg":"Setting comments for PR 588 to: [0xc0001301c0]","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
```

Then Yaml lint status completed successfully: https://dashboard.dogfooding.tekton.dev/#/namespaces/tektonci/taskruns/plumbing-yamllint-pr-complete-2kv2k?step=update-check-status
Not sure why it's not reflected on GitHub side.
```
[pr-source-pr-rh6q6] {"level":"info","ts":1600771732.2642784,"caller":"pullrequest-init/main.go:57","msg":"RUNNING DOWNLOAD!","resource_type":"pullrequest","mode":"download"}
[pr-source-pr-rh6q6] {"level":"info","ts":1600771732.2643507,"caller":"pullrequest/api.go:54","msg":"finding pr","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-rh6q6] {"level":"info","ts":1600771732.769296,"caller":"pullrequest/api.go:61","msg":"finding combined status","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-rh6q6] {"level":"info","ts":1600771732.861902,"caller":"pullrequest/api.go:72","msg":"finding comments: %v&{0xc00007aa20 tektoncd/plumbing 588 0xc00000e580}","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-rh6q6] {"level":"info","ts":1600771733.1814404,"caller":"pullrequest/api.go:77","msg":"found comments: %v[0xc000246ee0]","resource_type":"pullrequest","mode":"download","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}


[update-check-status] Previous status: {'State': 'pending', 'Label': 'plumbing-yamllint', 'Desc': 'Job Triggered.', 'Target': 'https://dashboard.dogfooding.tekton.dev/#/namespaces/tektonci/pipelineruns/tekton-yamllint-q64xj?pipelineTask=lint'}
[update-check-status] New status: {'State': 'success', 'Label': 'plumbing-yamllint', 'Desc': 'Job Finished.', 'Target': 'https://dashboard.dogfooding.tekton.dev/#/namespaces/tektonci/pipelineruns/tekton-yamllint-q64xj?pipelineTask=lint'}

[pr-source-pr-577h4] {"level":"info","ts":1600771735.4113164,"caller":"pullrequest-init/main.go:68","msg":"RUNNING UPLOAD!","resource_type":"pullrequest","mode":"upload"}
[pr-source-pr-577h4] {"level":"info","ts":1600771735.4164917,"caller":"pullrequest/api.go:114","msg":"Syncing resource: &{PR:0xc000110000 Statuses:[0xc000152180 0xc0001521c0 0xc000152200 0xc000152240 0xc000152280] Comments:[0xc0000fc1c0] Manifests:map[comments:map[696644952:true] labels:map[approved:true kind%2Fbug:true lgtm:true size%2FXS:true]]}","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-577h4] {"level":"info","ts":1600771735.7940307,"caller":"pullrequest/api.go:285","msg":"Looking for existing status on 016d843048266c6400dc4d81b57c256e035e2b51","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-577h4] {"level":"info","ts":1600771735.9536781,"caller":"pullrequest/api.go:301","msg":"Skipping setting EasyCLA because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-577h4] {"level":"info","ts":1600771735.9577587,"caller":"pullrequest/api.go:301","msg":"Skipping setting check-pr-has-kind-label because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-577h4] {"level":"info","ts":1600771735.9578452,"caller":"pullrequest/api.go:301","msg":"Skipping setting plumbing-golang-lint because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-577h4] {"level":"info","ts":1600771735.95787,"caller":"pullrequest/api.go:311","msg":"Creating status plumbing-yamllint on 016d843048266c6400dc4d81b57c256e035e2b51","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-577h4] {"level":"info","ts":1600771736.3508537,"caller":"pullrequest/api.go:301","msg":"Skipping setting tide because it already matches","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-577h4] {"level":"info","ts":1600771736.350954,"caller":"pullrequest/api.go:184","msg":"Setting comments for PR 588 to: [0xc0000fc1c0]","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
```

What is strange is the "creating status" on the complete... it should be updating status instead?
```
{"level":"info","ts":1600771735.95787,"caller":"pullrequest/api.go:311","msg":"Creating status plumbing-yamllint on 016d843048266c6400dc4d81b57c256e035e2b51","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
```

**Comment by afrittoli** [comment]
I checked with the next run, and it said the same "creating status"... only it worked.

**Comment by afrittoli** [comment]
It looks like the culprit was a different github update job, the golang one:
```
[pr-source-pr-vkhqw] {"level":"info","ts":1600771736.8803253,"caller":"pullrequest/api.go:311","msg":"Creating status plumbing-golang-lint on 016d843048266c6400dc4d81b57c256e035e2b51","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
[pr-source-pr-vkhqw] {"level":"info","ts":1600771737.1873493,"caller":"pullrequest/api.go:311","msg":"Creating status plumbing-yamllint on 016d843048266c6400dc4d81b57c256e035e2b51","resource_type":"pullrequest","mode":"upload","provider":"github","owner":"tektoncd","repo":"plumbing","pr":"588"}
```

The golang job found a change in the yaml job, so it most likely revert back to pending...

**Pull request merged**
