### PR TITLE
Add an openssh server docker image to our infra

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

This is going to be used to setup secure tunnels.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind feature

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Comment by afrittoli** [comment]
/mario build tekton/images/openssh-server openssh-server:mario

**Pull request merged**
