### PR TITLE
Remove sbwsg from rotation and owners

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

Removes sbwsg from buildcaptain rotation, starting in October, and plumbing owners file.

I'll make an equivalent PR in community for `org/org.yaml`

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@sbwsg sorry to see you go

**Comment by vdemeester** [comment]
@sbwsg same as @afrittoli said 😓 
/lgtm

**Pull request merged**
