### PR TITLE
Remove the extra labels from the github-set-status

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

As part of https://github.com/tektoncd/plumbing/pull/969 I added some
extra labels, however the values in those params are not always fit to
be label values and are causing the taskrun to not be created.

Remove the extra labels but keep the new naming format.
Also restore the checkName as part of the GitHub notification taskrun, since
we may be running more than one CI job per GitHub event.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind misc

### CODE REVIEW

**Comment by afrittoli** [comment]
@dibyom @abayer Would you mind helping getting this merged, so that I can finally restore sync of git to dogfooding?

**Review by dibyom — APPROVED** [review]
/lgtm

**Pull request merged**
