### PR TITLE
Reduce dashboard integration tests combinations

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR reduces dashboard integration tests combinations.

Lots of failures happen since we added new combinations, seems to be related to the load it generates on the cluster.

/cc @vdemeester @afrittoli @wlynch 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by eddycharly** [comment]
Thank you @sbwsg, i think we will need to update the branch protection on the repo too.

**Comment by vdemeester** [comment]
> Thank you @sbwsg, i think we will need to update the branch protection on the repo too.

will do :wink:

**Pull request merged**
