### PR TITLE
Add quotes for valid YAML in yamllint job config

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add quotes for valid YAML in yamllint job config

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
Still not working, looking into it

**Comment by vdemeester** [comment]
This one can be closed now :angel: 
/close

**Pull request closed without merging**
