### PR TITLE
The latest (unlreased) version of triggers wants bindings

### PR DESCRIPTION
**Pull request by afrittoli**
And I want to use the latest and greatest from triggers on
dogfooding, so updating all existing event listeners.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by dibyom** [comment]
Now that we have https://github.com/tektoncd/triggers/pull/242 merged, I think we can remove the hold on this one 👼

**Comment by afrittoli** [comment]
\o/
We need do update triggers on the cluster first though.

**Comment by afrittoli** [comment]
Handled in a different PR

**Pull request closed without merging**
