### PR TITLE
Change the last master reference to main 🧙

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

With this, I think the whole move from master to main will be taken
care of from the plumbing perspective.

/cc @afrittoli @ImJasonH @bobcatfish 
/cc @tektoncd/plumbing-maintainers 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
/approve

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Pull request merged**
