### PR TITLE
Add Results CI trigger to tektonci dogfooding eventlistener.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Trigger config definitions can be found here: https://github.com/tektoncd/results/tree/main/tekton

Trigger configs are not deployed automatically yet - this will be added
in a future PR.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind misc

### CODE REVIEW

**Comment by dibyom** [comment]
Verified that the results-ci trigger exists in the tektonci namespace

/approve

**Comment by afrittoli** [comment]
Sorry I arrived late to review this 🙏 

The `tekton/ci` folder is the legacy webhook, where CI jobs use pipeline resources and conditions and triggers embedded in eventl listeners. The `tekton/ci-workspace` folder is the new webhook, with results, workspaces and triggers as separated resources.

Since results owns its own trigger, it'd be probably better for its jobs to be under `ci-workspace`. This way the plumbing CD job would have no dependency to the trigger from the `triggers` repo. Besides I hope eventually to retire the old webhook and migrate all jobs to the new one.

**Pull request merged**
