### PR TITLE
Update plumbing reference from master to main 🪄

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes
This updates any reference to tektoncd/plumbing master branch to main
as we are renaming branches.

This is gonna be a bit of a "chicken-and-egg" situation, so we may
need to get this in "just" after renaming and apply things manually to
get everything back up correctly.

Related to tektoncd/plumbing#681

/cc @afrittoli @bobcatfish @ImJasonH 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind cleanup

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by ImJasonH — APPROVED** [review]

**Comment by vdemeester** [comment]
/hold
Will unhold tomorrow morning 😉

**Review by afrittoli — COMMENTED** [review]
/approve
/lgtm

**Comment by afrittoli** [comment]
Thanks for doing this! 🙏 🤞

**Pull request merged**
