### PR TITLE
For tekton/images/tkn build:

### PR DESCRIPTION
**Pull request by T0MASD**
# Changes

For tekton/images/tkn build:

- Add build step
- Update arch lookup using go env
- Add os lookup using go env
- Copy single binary to the final image

/kind bug

Supported kinds are: bug, cleanup, design, documentation, feature, flake, misc, question, tep

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

fixes https://github.com/tektoncd/plumbing/issues/1222

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by afrittoli** [comment]
Sorry @T0MASD - we've been working on some changes to CI - hopefully it will work now.

**Comment by afrittoli** [comment]
```shell
(...)
INFO[0014] args: [-c GOARCH=$(go env GOARCH)     GOOS=$(go env GOOS)     && wget -O- [https://github.com/tektoncd/cli/releases/download/v${TKN_VERSION}/tkn_${TKN_VERSION}_${GOOS}_${GOARCH}.tar.gz](https://github.com/tektoncd/cli/releases/download/v$%7BTKN_VERSION%7D/tkn_$%7BTKN_VERSION%7D_$%7BGOOS%7D_$%7BGOARCH%7D.tar.gz) | tar zxf - -C /usr/local/bin] 
INFO[0014] Running: [/bin/sh -c GOARCH=$(go env GOARCH)     GOOS=$(go env GOOS)     && wget -O- [https://github.com/tektoncd/cli/releases/download/v${TKN_VERSION}/tkn_${TKN_VERSION}_${GOOS}_${GOARCH}.tar.gz](https://github.com/tektoncd/cli/releases/download/v$%7BTKN_VERSION%7D/tkn_$%7BTKN_VERSION%7D_$%7BGOOS%7D_$%7BGOARCH%7D.tar.gz) | tar zxf - -C /usr/local/bin] 
Connecting to [github.com](http://github.com/) (140.82.112.4:443)
wget: server returned error: HTTP/1.1 404 Not Found
tar: invalid magic
tar: short read
error building image: error building stage: failed to execute command: waiting for process to exit: exit status 1
```

**Comment by T0MASD** [comment]
My bad, didn't check that `GOARCH` on x86_64 returns `amd64` not x86_64. Will need to better understand your release process  and how files are generated

/hold

**Comment by T0MASD** [comment]
I had raised a PR https://github.com/tektoncd/cli/pull/1745 which introduces replacements for arm64 in goreleaser file, if accepted there will be downloads available on the url matching this PR

**Comment by afrittoli** [comment]
https://github.com/tektoncd/cli/pull/1745 is merged - is it ok to un-hold this one now?

**Comment by T0MASD** [comment]
@afrittoli thanks for follow up, the tests are passing this is good to merge from my perspective

**Review by vdemeester — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
