### PR TITLE
dependabot: Add go modules + labels.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

dependabot: Add go modules + labels for any directory that had a go.mod file.

List roughly generated via:

```sh
$ for p in `find . | grep go.mod`; do
p="${p:1:-7}"
echo "  - package-ecosystem: \"gomod\"
    directory: \"${p}\"
    schedule:
      interval: \"weekly\"
    labels:
      - \"ok-to-test\"
      - \"dependencies\"
      - \"release-note-none\"
      - \"kind/misc\""
done
```

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by wlynch** [comment]
/cc @lbernick 

If we merge this dependabot should pick up go-licenses updates.

**Comment by lbernick** [comment]
/lgtm

Are plumbing unittests flaky?

**Comment by wlynch** [comment]
There's something funky going on with the plumbing tests - they don't look like they ever terminate https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_plumbing/1376/plumbing-unit-tests/1632792914436296704

🤷

**Pull request merged**
