### PR TITLE
Update base image used by test-runner image

### PR DESCRIPTION
**Pull request by ImJasonH**
# Changes

Update the base image used by the Prow test-runner image, to one that will remain up-to-date.

The previous base image was pinned to a specific date, which means we'd have to update it manually before future builds.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ n/a ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ y ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
ping @ImJasonH, needs a rebase :stuck_out_tongue:

**Comment by afrittoli** [comment]
goomba at your service! </p>Cloud not build the requested image. Please check the <a href="http://35.222.249.224/?buildid=4960f878-1a30-4695-a18f-b2fab8684e99&namespace=mario">build logs</a>

**Comment by bobcatfish** [comment]
Maybe we can rebase this for @ImJasonH :thinking:

**Comment by dibyom** [comment]
The file has been moved to https://github.com/tektoncd/plumbing/blob/master/tekton/images/test-runner/Dockerfile

Do we even need this anymore or can we close this?

**Comment by vdemeester** [comment]
Yeah I think we should close it :angel:. We can update the image (in the new place) but I tend to prefer to focus on dogfooding as long as this image works for all prow-enabled projects. Relying on a mater would make the image change at anytime and could cause some.. problems randomly :sweat_smile:

**Pull request closed without merging**
