### PR TITLE
Update tkn to v0.12.0

### PR DESCRIPTION
**Pull request by danielhelfand**
Updating tkn to the latest major version release (v0.12.0)

# Submitter Checklist

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Review by savitaashture — APPROVED** [review]
/approve

**Review by vdemeester — APPROVED** [review]
/meow

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Pull request merged**
