### PR TITLE
Fix the ko deployment for the logs app

### PR DESCRIPTION
**Pull request by afrittoli**
The deployment does not need a "command" anymore, since that's
set by ko to the ko-app binary included in the docker image.

Since the server requires the static files templates/entries.html,
adding those to kodata, and adding the ability in main.go to load
them from KO_DATA_PATH.

Note that having a folder under kodata requires a recent version
of ko to build.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@sbwsg @vdemeester

**Comment by afrittoli** [comment]
The pod seems to be running fine with this in the `dogfooding` cluster:

```
$ kubectl logs pipelinerun-logs-deployment-54cc8756b6-w555d
2019/10/23 11:21:46 Serving 0.0.0.0:9999
```

**Comment by afrittoli** [comment]
I fixed the container port that did not match the serving port.
Now if I add an ingress I can curl the service.

**Comment by sbwsg** [comment]
:+1: thanks @afrittoli

**Pull request merged**
