### PR TITLE
prow: fix query for stale, rotten and close issues

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

As of today, an issue is close after 30 days (without necessarly been
rotten) because it does filter them out. Same for lifecycle/rotten, it
does not do 30 + 90 days, but only 90 days.

It seemed there was way too much issue being closed :sweat_smile: 

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

/cc @jerop @afrittoli @bobcatfish 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
I don't understand the query syntax but thanks for fixing this anyway @vdemeester ! :D

**Comment by vdemeester** [comment]
> I don't understand the query syntax but thanks for fixing this anyway @vdemeester ! :D

`-label:lifecycle/frozen` mean "filter issues/prs with label `lifecycle/frozen`" from the query. `label:lifecycle/rotten` (with the dash `-`) means filter those in (aka this will return all issues with that label). The filter was the same for `stale`, `rotten` and `close`, meaning we would apply the 2 at the same time (with the same time base), hence issues being closed after only 30 days of inactivity. Now, we do apply the `rotten` part only on the issues that already have the `lifecycle/stale` label. And *as* adding the comment count as an activity, the 30 days + 90 days are respected :wink: :stuck_out_tongue_closed_eyes:

**Pull request merged**
