### PR TITLE
Added Multiarch support to gcr.io/tekton-releases/dogfooding/tkn:late…

### PR DESCRIPTION
**Pull request by snehlatamohite**
…st container

# Changes
Hi All,

I have updated tekton/images/tkn/Dockerfile to support multiarch container creation for gcr.io/tekton-releases/dogfooding/tkn:latest

Please review.

Thanks,
Snehlata Mohite. 
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by dibyom** [comment]
@snehlatamohite thanks for opening the PR. Could you sign the CLA?

**Comment by snehlatamohite** [comment]
@dibyom - Sorry for delay CLA has been signed.

**Pull request merged**
