### PR TITLE
Updated cronjobs to publish from gcr.io to ghcr.io

### PR DESCRIPTION
**Pull request by LiteBrick204**
# Changes
/kind feature
This PR is for #2223 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@LiteBrick204 thank you for your contribution and welcome to the Tekton community!

**Comment by afrittoli** [comment]
@LiteBrick204 could you please sign the Tekton CLA (see the link in the check above):

image

**Comment by LiteBrick204** [comment]
I will create a new PR for this as well

**Pull request closed without merging**
