### PR TITLE
tekton/images: remove openssh-server…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes
I don't think it is used anywhere, so let's not have to maintain it.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
@afrittoli I think the image-build failure is "kind-of" expected 😅

**Review by wlynch — APPROVED** [review]
/lgtm

**Comment by vdemeester** [comment]
Related to #1839. @afrittoli I think with the way the ci is currently setup, we can't get the `plumbing-image-build` green, do we want to "force" merge, or ?

**Pull request merged**
