### PR TITLE
Add resource requests and limits to chains Prow jobs

### PR DESCRIPTION
**Pull request by abayer**
# Changes

I noticed that these are prone to spiking CPU, so might as well make them the next to get requests/limits.

/kind misc

/assign @afrittoli @vdemeester 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Comment by abayer** [comment]
@afrittoli Prow never received your lgtm, mind trying again? =)

**Pull request merged**
