### PR TITLE
Restore compatibility with triggers v0.5.0

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Change binding  names to binding refs in event listeners.

Related to https://github.com/tektoncd/triggers/issues/607

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind bug

### CODE REVIEW

**Comment by sbwsg** [comment]
Hmm, looks like it might just need a rebase to fix these errors?

```
[2020-06-15T14:16:21Z] (git/git.go:136) Successfully cloned https://github.com/tektoncd/plumbing @ 39f63373353f3c567f3fc277a63effb199264153 (HEAD) in path /workspace/source
[2020-06-15T14:16:21Z] (git/git.go:177) Successfully initialized and updated submodules in path /workspace/source
[2020-06-15T14:16:21Z] + set -o pipefail
[2020-06-15T14:16:21Z] + BACK='HEAD~1'
[2020-06-15T14:16:21Z] + cd /workspace/source
[2020-06-15T14:16:21Z] + grep+ -E 'tekton/images/alpine-git-nonroot/**'
[2020-06-15T14:16:21Z] git diff-tree --no-commit-id --name-only -r HEAD 'HEAD~1'
[2020-06-15T14:16:43Z] Trigger the reset of status for plumbing-yamllint
[2020-06-15T14:16:45Z] Trigger the reset of status for plumbing-images-build
[2020-06-15T14:16:55Z] (git/git.go:136) Successfully cloned https://github.com/tektoncd/plumbing @ 39f63373353f3c567f3fc277a63effb199264153 (HEAD) in path /workspace/source
[2020-06-15T14:16:55Z] (git/git.go:177) Successfully initialized and updated submodules in path /workspace/source
[2020-06-15T14:16:56Z] + yamllint buildbot/config mariobot/config pipelinerun-logs/config boskos gubernator prow robocat tekton
[2020-06-15T14:17:01Z] robocat/cadmin/100-namespace.yaml
[2020-06-15T14:17:01Z] 26:16 warning too few spaces before comment (comments)
[2020-06-15T14:17:01Z] 31:22 warning too few spaces before comment (comments)
[2020-06-15T14:17:01Z]
[2020-06-15T14:17:01Z] tekton/cronjobs/folder-cd-cron-base/trigger-resource-cd.yaml
[2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
[2020-06-15T14:17:01Z]
[2020-06-15T14:17:01Z] tekton/cronjobs/helm-cd-cron-base/trigger-resource-cd.yaml
[2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
[2020-06-15T14:17:01Z]
[2020-06-15T14:17:01Z] tekton/cronjobs/tekton-service-cd-cron-base/trigger-resource-cd.yaml
[2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
[2020-06-15T14:17:01Z]
[2020-06-15T14:17:01Z] tekton/cronjobs/configmap-cd-cron-base/trigger-resource-cd.yaml
[2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
[2020-06-15T14:17:01Z]
[2020-06-15T14:17:02Z] (git/git.go:136) Successfully cloned https://github.com/tektoncd/plumbing @ 39f63373353f3c567f3fc277a63effb199264153 (HEAD) in path /workspace/source
[2020-06-15T14:17:02Z] (git/git.go:177) Successfully initialized and updated submodules in path /workspace/source
[2020-06-15T14:17:03Z] + cd /workspace/source/
[2020-06-15T14:17:03Z] + golangci-lint run --verbose
[2020-06-15T14:17:04Z] level=info msg="[config_reader] Config search paths: [./ /workspace/source /workspace /]"
[2020-06-15T14:17:05Z] level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
[2020-06-15T14:17:05Z] level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
[2020-06-15T14:17:25Z] level=info msg="[loader] Go packages loading at mode 575 (types_sizes|deps|files|compiled_files|exports_file|imports|name) took 19.772750836s"
[2020-06-15T14:17:25Z] level=info msg="[runner/enabledLinters] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
[2020-06-15T14:17:25Z] level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 1.303942ms"
[2020-06-15T14:17:27Z] level=info msg="[runner/unused/goanalysis] analyzers took 117.497636ms with top 10 stages: buildssa: 108.102348ms, U1000: 9.395288ms"
[2020-06-15T14:17:35Z] level=info msg="[runner/goanalysis_metalinter/goanalysis] analyzers took 14.487979955s with top 10 stages: buildssa: 10.637253486s, inspect: 1.327492921s, ctrlflow: 701.421007ms, fact_purity: 648.66643ms, printf: 595.258946ms, fact_deprecated: 506.461442ms, SA2003: 13.9734ms, SA5009: 7.154122ms, vrp: 6.162217ms, SA5005: 4.030907ms"
[2020-06-15T14:17:35Z] level=info msg="[runner/max_same_issues] 4/7 issues with text \"printf: Printf call has error-wrapping directive %w\" were hidden, use --max-same-issues"
[2020-06-15T14:17:35Z] level=info msg="[runner] Issues before processing: 19, after processing: 7"
[2020-06-15T14:17:35Z] level=info msg="[runner] Processors filtering stat (out/in): nolint: 15/15, uniq_by_line: 11/15, cgo: 19/19, filename_unadjuster: 19/19, exclude-rules: 15/15, skip_files: 19/19, max_from_linter: 7/7, path_shortener: 7/7, max_per_file_from_linter: 11/11, max_same_issues: 7/11, source_code: 7/7, skip_dirs: 19/19, identifier_marker: 19/19, exclude: 15/19, path_prettifier: 19/19, autogenerated_exclude: 19/19, diff: 11/11"
[2020-06-15T14:17:35Z] level=info msg="[runner] processing took 2.482098ms with stages: exclude: 841.114µs, nolint: 589.219µs, identifier_marker: 484.3µs, path_prettifier: 155.704µs, skip_dirs: 152.554µs, autogenerated_exclude: 118.11µs, source_code: 57.784µs, max_same_issues: 50.738µs, uniq_by_line: 8.431µs, cgo: 5.601µs, path_shortener: 5.494µs, max_from_linter: 4.241µs, filename_unadjuster: 3.386µs, max_per_file_from_linter: 3.034µs, diff: 874ns, skip_files: 795ns, exclude-rules: 719ns"
[2020-06-15T14:17:35Z] level=info msg="[runner] linters took 9.855070064s with stages: goanalysis_metalinter: 8.126919804s, unused: 1.725522976s"
[2020-06-15T14:17:35Z] level=info msg="File cache stats: 1 entries of total size 4.3KiB"
[2020-06-15T14:17:35Z] dummy.go:23:6: func `main` is unused (unused)
[2020-06-15T14:17:35Z] scripts/dummy.go:23:6: func `main` is unused (unused)
[2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:171:6: func `addPrBody` is unused (unused)
[2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:48:3: ineffectual assignment to `payload` (ineffassign)
[2020-06-15T14:17:35Z] payload := []byte(`{}`)
[2020-06-15T14:17:35Z] ^
[2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:56:5: printf: Printf call has error-wrapping directive %w (govet)
[2020-06-15T14:17:35Z] log.Printf("failed to read request body: %w", err)
[2020-06-15T14:17:35Z] ^
[2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:62:5: printf: Printf call has error-wrapping directive %w (govet)
[2020-06-15T14:17:35Z] log.Printf("No body received: %w", bodyError)
[2020-06-15T14:17:35Z] ^
[2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:68:4: printf: Printf call has error-wrapping directive %w (govet)
[2020-06-15T14:17:35Z] log.Printf("failed to read request body: %w", err)
[2020-06-15T14:17:35Z] ^
[2020-06-15T14:17:35Z] level=info msg="Memory: 306 samples, avg is 101.7MB, max is 271.4MB"
[2020-06-15T14:17:35Z] level=info msg="Execution took 30.874839466s"
```

**Comment by afrittoli** [comment]
> Hmm, looks like it might just need a rebase to fix these errors?
> 
> ```
> [2020-06-15T14:16:21Z] (git/git.go:136) Successfully cloned https://github.com/tektoncd/plumbing @ 39f63373353f3c567f3fc277a63effb199264153 (HEAD) in path /workspace/source
> [2020-06-15T14:16:21Z] (git/git.go:177) Successfully initialized and updated submodules in path /workspace/source
> [2020-06-15T14:16:21Z] + set -o pipefail
> [2020-06-15T14:16:21Z] + BACK='HEAD~1'
> [2020-06-15T14:16:21Z] + cd /workspace/source
> [2020-06-15T14:16:21Z] + grep+ -E 'tekton/images/alpine-git-nonroot/**'
> [2020-06-15T14:16:21Z] git diff-tree --no-commit-id --name-only -r HEAD 'HEAD~1'
> [2020-06-15T14:16:43Z] Trigger the reset of status for plumbing-yamllint
> [2020-06-15T14:16:45Z] Trigger the reset of status for plumbing-images-build
> [2020-06-15T14:16:55Z] (git/git.go:136) Successfully cloned https://github.com/tektoncd/plumbing @ 39f63373353f3c567f3fc277a63effb199264153 (HEAD) in path /workspace/source
> [2020-06-15T14:16:55Z] (git/git.go:177) Successfully initialized and updated submodules in path /workspace/source
> [2020-06-15T14:16:56Z] + yamllint buildbot/config mariobot/config pipelinerun-logs/config boskos gubernator prow robocat tekton
> [2020-06-15T14:17:01Z] robocat/cadmin/100-namespace.yaml
> [2020-06-15T14:17:01Z] 26:16 warning too few spaces before comment (comments)
> [2020-06-15T14:17:01Z] 31:22 warning too few spaces before comment (comments)
> [2020-06-15T14:17:01Z]
> [2020-06-15T14:17:01Z] tekton/cronjobs/folder-cd-cron-base/trigger-resource-cd.yaml
> [2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
> [2020-06-15T14:17:01Z]
> [2020-06-15T14:17:01Z] tekton/cronjobs/helm-cd-cron-base/trigger-resource-cd.yaml
> [2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
> [2020-06-15T14:17:01Z]
> [2020-06-15T14:17:01Z] tekton/cronjobs/tekton-service-cd-cron-base/trigger-resource-cd.yaml
> [2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
> [2020-06-15T14:17:01Z]
> [2020-06-15T14:17:01Z] tekton/cronjobs/configmap-cd-cron-base/trigger-resource-cd.yaml
> [2020-06-15T14:17:01Z] 19:26 warning too few spaces before comment (comments)
> [2020-06-15T14:17:01Z]
> [2020-06-15T14:17:02Z] (git/git.go:136) Successfully cloned https://github.com/tektoncd/plumbing @ 39f63373353f3c567f3fc277a63effb199264153 (HEAD) in path /workspace/source
> [2020-06-15T14:17:02Z] (git/git.go:177) Successfully initialized and updated submodules in path /workspace/source
> [2020-06-15T14:17:03Z] + cd /workspace/source/
> [2020-06-15T14:17:03Z] + golangci-lint run --verbose
> [2020-06-15T14:17:04Z] level=info msg="[config_reader] Config search paths: [./ /workspace/source /workspace /]"
> [2020-06-15T14:17:05Z] level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
> [2020-06-15T14:17:05Z] level=info msg="[lintersdb] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
> [2020-06-15T14:17:25Z] level=info msg="[loader] Go packages loading at mode 575 (types_sizes|deps|files|compiled_files|exports_file|imports|name) took 19.772750836s"
> [2020-06-15T14:17:25Z] level=info msg="[runner/enabledLinters] Active 10 linters: [deadcode errcheck gosimple govet ineffassign staticcheck structcheck typecheck unused varcheck]"
> [2020-06-15T14:17:25Z] level=info msg="[runner/filename_unadjuster] Pre-built 0 adjustments in 1.303942ms"
> [2020-06-15T14:17:27Z] level=info msg="[runner/unused/goanalysis] analyzers took 117.497636ms with top 10 stages: buildssa: 108.102348ms, U1000: 9.395288ms"
> [2020-06-15T14:17:35Z] level=info msg="[runner/goanalysis_metalinter/goanalysis] analyzers took 14.487979955s with top 10 stages: buildssa: 10.637253486s, inspect: 1.327492921s, ctrlflow: 701.421007ms, fact_purity: 648.66643ms, printf: 595.258946ms, fact_deprecated: 506.461442ms, SA2003: 13.9734ms, SA5009: 7.154122ms, vrp: 6.162217ms, SA5005: 4.030907ms"
> [2020-06-15T14:17:35Z] level=info msg="[runner/max_same_issues] 4/7 issues with text \"printf: Printf call has error-wrapping directive %w\" were hidden, use --max-same-issues"
> [2020-06-15T14:17:35Z] level=info msg="[runner] Issues before processing: 19, after processing: 7"
> [2020-06-15T14:17:35Z] level=info msg="[runner] Processors filtering stat (out/in): nolint: 15/15, uniq_by_line: 11/15, cgo: 19/19, filename_unadjuster: 19/19, exclude-rules: 15/15, skip_files: 19/19, max_from_linter: 7/7, path_shortener: 7/7, max_per_file_from_linter: 11/11, max_same_issues: 7/11, source_code: 7/7, skip_dirs: 19/19, identifier_marker: 19/19, exclude: 15/19, path_prettifier: 19/19, autogenerated_exclude: 19/19, diff: 11/11"
> [2020-06-15T14:17:35Z] level=info msg="[runner] processing took 2.482098ms with stages: exclude: 841.114µs, nolint: 589.219µs, identifier_marker: 484.3µs, path_prettifier: 155.704µs, skip_dirs: 152.554µs, autogenerated_exclude: 118.11µs, source_code: 57.784µs, max_same_issues: 50.738µs, uniq_by_line: 8.431µs, cgo: 5.601µs, path_shortener: 5.494µs, max_from_linter: 4.241µs, filename_unadjuster: 3.386µs, max_per_file_from_linter: 3.034µs, diff: 874ns, skip_files: 795ns, exclude-rules: 719ns"
> [2020-06-15T14:17:35Z] level=info msg="[runner] linters took 9.855070064s with stages: goanalysis_metalinter: 8.126919804s, unused: 1.725522976s"
> [2020-06-15T14:17:35Z] level=info msg="File cache stats: 1 entries of total size 4.3KiB"
> [2020-06-15T14:17:35Z] dummy.go:23:6: func `main` is unused (unused)
> [2020-06-15T14:17:35Z] scripts/dummy.go:23:6: func `main` is unused (unused)
> [2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:171:6: func `addPrBody` is unused (unused)
> [2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:48:3: ineffectual assignment to `payload` (ineffassign)
> [2020-06-15T14:17:35Z] payload := []byte(`{}`)
> [2020-06-15T14:17:35Z] ^
> [2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:56:5: printf: Printf call has error-wrapping directive %w (govet)
> [2020-06-15T14:17:35Z] log.Printf("failed to read request body: %w", err)
> [2020-06-15T14:17:35Z] ^
> [2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:62:5: printf: Printf call has error-wrapping directive %w (govet)
> [2020-06-15T14:17:35Z] log.Printf("No body received: %w", bodyError)
> [2020-06-15T14:17:35Z] ^
> [2020-06-15T14:17:35Z] tekton/ci/interceptors/add-pr-body/cmd/add-pr-body/main.go:68:4: printf: Printf call has error-wrapping directive %w (govet)
> [2020-06-15T14:17:35Z] log.Printf("failed to read request body: %w", err)
> [2020-06-15T14:17:35Z] ^
> [2020-06-15T14:17:35Z] level=info msg="Memory: 306 samples, avg is 101.7MB, max is 271.4MB"
> [2020-06-15T14:17:35Z] level=info msg="Execution took 30.874839466s"
> ```

Oh, I see, thanks

**Pull request merged**
