### PR TITLE
Initial work for TEP automation bot

### PR DESCRIPTION
**Pull request by abayer**
# Changes

This just adds the boilerplate (`config` directory, `tekton` directory, `Makefile`, `.ko.yaml`, a barebones `cmd/tepautomation/main.go`, and adding `bots/tep-automation` to PR builds), along with `pkg/tep`, which contains the structs used for representing various bits of TEP information and parsers for extracting TEP information from implementation PRs, TEP PRs, and TEP markdown.

It doesn't _do_ anything yet, but it lays the bedrock to build the real implementation off of, and will be followed up with code implementation for the custom task.

Note that there are bits (like https://github.com/tektoncd/plumbing/pull/995/files#diff-bfe82559c41313c6d051ab264e125a92622aa262dfdcf28ecfdd0d2c2f475a9eR149 and https://github.com/tektoncd/plumbing/pull/995/files#diff-bfe82559c41313c6d051ab264e125a92622aa262dfdcf28ecfdd0d2c2f475a9eR36) which are included in `pkg/tep` but don't serve any purpose with the code here in this PR. I just thought it was simpler for me to copy the whole `pkg/tep` from #983 over rather than tease out bits that may not be obvious in their usage til later.

This the first layer of a series of PRs replacing the more monolithic #983.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by abayer** [comment]
/assign @afrittoli 

Is this all I need to do in order to get a new subproject in plumbing to be built/tested/etc when a PR is opened?

**Comment by abayer** [comment]
/assign @jerop 

I know you've been digging into the monster PR at #983, but @lbernick persuaded me to split it up into multiple, smaller ones. =)

**Review by afrittoli — COMMENTED** [review]
Thanks @abayer for splitting this in parts and for driving this forward.
I still haven't reviewed it 😅 but I was wondering if in light of the current discussion about the TEP process possible upcoming changes, we should temporarily freeze this and resume once we have agreed on a new process? Hopefully next week after the meeting.

**Comment by abayer** [comment]
@afrittoli - Yeah, I kind of assumed we were putting it on hold for exactly that reason. =)

**Pull request closed without merging**
