### PR TITLE
Generate a buildcaptain rotation for 2021

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

Create a buildcaptain rotation csv starting on jan 1 2021
using the same rotation of names that we were using at end
of december.

Removed all the rotation overrides from 2020.

Here's the command I ran to generate the rotation:

```bash
go run ./cmd/generate-rotation-csv/main.go \
  -overrides ./rotation-overrides.csv \
  -start-date 2021-01-01 \
  -days 365 \
  -names wlynch,dibyo,nikthoma,sashture,sbws,jerop,vdemeest,andrea.frittoli \
  > ./rotation.csv
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by sbwsg** [comment]
Rebased on main.

**Review by savitaashture — COMMENTED** [review]
/lgtm

**Review by afrittoli — COMMENTED** [review]
Thank you!
/approve

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
