### PR TITLE
Increase the number of CD pipelines we notify about

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Send a notification to slack when any of the CD pipelines files.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind feature

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow

**Comment by bobcatfish** [comment]
So weird, the assign plugin is working but not trigger 🤔

**Pull request merged**
