### PR TITLE
Enable release-note and few other plugins 👼

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

… adding release-note only on tektoncd/pipeline for now.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli @bobcatfish @jerop 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
@vdemeester would you be able to explain a bit about the plugins you are enabling, how they work and what they do?

**Comment by jerop** [comment]
thanks for enabling the release-note plugin @vdemeester 🙏 

looks like we'll need to edit the [pull request template](https://github.com/tektoncd/pipeline/blob/master/.github/pull_request_template.md) with the `release-note` header
Screen Shot 2020-06-16 at 10 43 33 AM

/lgtm

**Comment by vdemeester** [comment]
@tekton-robot yes, the release-note works as @jerop commented (we will need to update the templates)
- project allows us to do `/project name-of-the-project` to add it to a project (so no need to have write access to the org or repo)
- retitle allows us to do `/retitle foo` to rename the title to "foo" (same, no need to have write access to do that)

**Comment by afrittoli** [comment]
Rebase required

**Pull request merged**
