### PR TITLE
Temporarly remove Jason from buildcop rotation 👮

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

There is good reason for it 👶🎉

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
@afrittoli yeah I was just lazy so I did a search-and-replace :stuck_out_tongue_closed_eyes:

**Comment by dibyom** [comment]
/lgtm

But I agree with @afrittoli, we should share the load

**Comment by vdemeester** [comment]
@dibyom @afrittoli yeah we need a "csv" generator :stuck_out_tongue: to update the csv easily :joy_cat:

**Comment by dibyom** [comment]
I think I can confirm that @wlynch is in :wink: 

/approve

**Pull request merged**
