### PR TITLE
Add post release file to Tekton install task and script

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Tekton triggers installation is now split into two files. The
second one can only be installed once CRDs are established.

To support this, split the tekton install task in three steps:
- install the main release file with overlays, like before
- wait for pods ready and CRD established that match the project
  being installed
- install the post release file, in any

In the script, set the default post file to "interceptors.yaml"
for triggers, to keep the script easy to use.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind misc

### CODE REVIEW

**Comment by afrittoli** [comment]
It works!  https://dashboard.dogfooding.tekton.dev/#/namespaces/default/taskruns/deploy-triggers-release-dogfooding-r8rdk?step=deploy-extra-manifest

**Review by vdemeester — APPROVED** [review]
/meow

**Pull request merged**
