### PR TITLE
Update Dashboard nightly release template

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

https://github.com/tektoncd/dashboard/issues/1969
~~Depends on https://github.com/tektoncd/dashboard/pull/2232~~ (merged and updated on dogfooding)

Update the template to support the new Dashboard release pipeline,
using params and workspaces instead of PipelineResources.

Based on the corresponding file used for tektoncd/pipeline, with
the disk request bumped to 2Gi instead of 1Gi.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @bobcatfish @afrittoli

**Review by afrittoli — COMMENTED** [review]
Thank you @AlanGreene /lgtm

**Pull request merged**
