### PR TITLE
Fix typo for tektoncd/pipeline postsubmit job 🙀

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

I don't know how I did that :joy_cat: :man_facepalming: 

/cc @bobcatfish @abayer 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by abayer** [comment]
Resolve the merge conflict! =)

**Comment by vdemeester** [comment]
@abayer done :hugs:

**Comment by bobcatfish** [comment]
haha IT SHOULD HAVE BEEN CALLED PIPELINES ALL ALONG 😅 

This mistake will haunt me all my life...

**Pull request merged**
