### PR TITLE
Update Dashboard integration tests to run on Kubernetes 1.25

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
Pipeline and triggers runs the tests on k8s 1.23 - should we have a consistent approach across projects?
Maybe we could do something like https://github.com/tektoncd/pipeline/pull/5767, i.e.

- on every PR, run full e2e tests against one version of k8s 
- on every PR, run smoke e2e tests against various versions of k8s
- run nightly tests on main against k8s version we only smoke test on PR

**Comment by AlanGreene** [comment]
Yes that's something we could consider. I'll close this for now.

**Comment by afrittoli** [comment]
I created https://github.com/tektoncd/plumbing/issues/1288 to track this

**Pull request closed without merging**
