### PR TITLE
E2E use video-skip-flag in dashboard tests failures.

### PR DESCRIPTION
**Pull request by Basavaraju-G**
# Changes
use E2E_VIDEO flag to skip video recording in tekton dashboard e2e CI failures.

In addition, categorize the changes you're making using the "/kind" Prow command, example:

/kind misc
Supported kinds are: bug, cleanup, design, documentation, feature, flake, misc, question, tep
-->

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by dibyom** [comment]
> use E2E_VIDEO flag to skip video recording in tekton dashboard e2e CI failures.

We can record videos?? 😲

**Comment by AlanGreene** [comment]
> We can record videos?? 😲

Yes, it took a while but I finally got around to adding proper browser E2E tests (using [Cypress](https://www.cypress.io/)) a few weeks ago for the Dashboard and they record video by default when run in CI mode. If a test fails, its video is uploaded to GCS with the rest of the prow logs once the job is finished, i.e. `/tekton-prow/pr-logs/pull/tektoncd_dashboard/<PR_number>/pull-tekton-dashboard-integration-tests/<job-id>/`

They can also be run locally in headless mode which is what we run in CI (records video locally), or in interactive mode with a functional browser, dev tools, etc.

**Comment by Basavaraju-G** [comment]
@dlorenc @wlynch would you please review This PR?

**Pull request merged**
