### PR TITLE
Fix publish.yaml for pr-commenter

### PR DESCRIPTION
**Pull request by abayer**
# Changes

The `VERSION_TAG` stuff doesn't work for some reason, and is not necessary anyway, since `params.versionTag` is available. So let's get this in sync with what we're doing in pr-status-updater.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
The ${VERSION_TAG} is within single quotes, you'll need to close the single quotes first.
See my comment on https://github.com/tektoncd/plumbing/pull/1212 - we should not pass parameters directly in the script ideally.

**Comment by abayer** [comment]
In the pr-status-updater work, I hit this too, and switching to double quotes didn't fix it for some reason. I'll try again later and leave this as is for now.

**Comment by afrittoli** [comment]
> In the pr-status-updater work, I hit this too, and switching to double quotes didn't fix it for some reason. I'll try again later and leave this as is for now.

Switching to double quotes does not work, you need single quotes and close them before the variable and the open them again after the variable.

The example in https://github.com/tektoncd/plumbing/pull/1212#issuecomment-1256036946 works on bash/zsh

**Comment by afrittoli** [comment]
@abayer are you still working on this one?

**Review by dibyom — APPROVED** [review]

**Comment by afrittoli** [comment]
/hold

@abayer @dibyom please do not merge this as it is, we don't want to use params in scripts directly for security reasons.
I will propose a PR update that uses env variables instead

**Comment by abayer** [comment]
I don't think I can lgtm this, since it started as a PR of mine. =) But it looks fine.

**Comment by abayer** [comment]
Oh, worth mentioning that `pr-status-updater` is using `params.versionTag` currently as well, so that should probably be switched too?

**Pull request merged**
