### PR TITLE
Update test-infra import to place tools in $GOPATH/src/knative.dev/...

### PR DESCRIPTION
**Pull request by ImJasonH**
# Changes

This installs knative/test-infra deps into `$GOPATH/src/knative.dev/test-infra` instead of at their old path.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ n/a ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ y ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by bobcatfish** [comment]
@ImJasonH before this change did the scripts not work? Also does this mean we have to re-vendor them all?

**Comment by vdemeester** [comment]
@bobcatfish It works fine, it’s just not in the correct folder compared to upstream. 
/lgtm

**Comment by bobcatfish** [comment]
Just trying something out, nothing to see here *whistling*

/run try-out-tekton

**Comment by vdemeester** [comment]
/lgtm cancel
(to unblock tide… waiting for @ImJasonH to make the google cla green :stuck_out_tongue: )

**Comment by vdemeester** [comment]
ping @ImJasonH

**Comment by afrittoli** [comment]
@ImJasonH this will need a rebase. And something to unlock the CLA bot?

**Pull request closed without merging**
