### PR TITLE
CI Interceptors: Use Environment Variables instead of Parameters

### PR DESCRIPTION
**Pull request by jerop**
# Changes

Today, the tasks and pipelines in ci/interceptors  use parameters in the scripts which are interpolated.

As described in #971, this is fragile and poses a security risk.

In this change, we migrate to using environment variables which are not interpolated in scripts.

* [x]  ./tekton/ci/interceptors/add-pr-body/tekton/publish.yaml:
* [x]  ./tekton/ci/interceptors/add-pr-body/tekton/release-pipeline.yaml:
* [x]  ./tekton/ci/interceptors/add-team-members/tekton/publish.yaml:
* [x]  ./tekton/ci/interceptors/add-team-members/tekton/release-pipeline.yaml:

Related issue: #971

cc @sbwsg 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by sbwsg** [comment]
This looks great, thanks for tackling!

/lgtm

Making the `$(params.foo)` -> `${PARAM_FOO}` change consistently (and reviewing it for consistency) are both quite tricky!

**Comment by jerop** [comment]
@sbwsg fixed the other scripts under `./tekton/ci/interceptors` in this pr (was previously `./tekton/ci/interceptors/add-pr-body/tekton/publish.yaml` only)

**Review by dibyom — APPROVED** [review]

**Comment by sbwsg** [comment]
Have read through again and this all looks good from my pov!

**Pull request merged**
