### PR TITLE
prow: env vars values needs to be strings 😅

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Otherwise, it is broken 😝. And… the prow config is currently broken :wink: 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli @gabemontero @nikhil-thomas @bobcatfish @sbwsg 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
> I'd wonder how you could detect this as part of the CI for branches?

I think a small "validation" that tries to unmarshall the configuration would work (not sure if it's something available in prow or not, but it should be "relatively" simple to write.

**Comment by gabemontero** [comment]
thank you @vdemeester !!

**Comment by gabemontero** [comment]
is it me @vdemeester or do some of those jobs seem stuck ?

check-pr-has-label, plumbing-golang-lint, plumbing-yamllint

**Pull request merged**
