### PR TITLE
Bump ko version in ko-gcloud to v0.5.1 from v0.5.0

### PR DESCRIPTION
**Pull request by a-roberts**
# Changes

Fixes https://github.com/tektoncd/plumbing/issues/426 - hopefully. Todo build ourselves and prove it fixes this, and check the upgrade is safe for everything else in Tekton.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by a-roberts** [comment]
Let's see if this works

/kind/bug

gonna treat it as a bug because 0.5.0 has an issue whereby the files it produces, we think, have the wrong permissions

**Comment by sbwsg** [comment]
Digging back through some slightly older issues I spy https://github.com/tektoncd/plumbing/issues/370 which hasn't closed out yet and a thread on ko that I think suggests this is fixed in 0.5.1?  https://github.com/google/ko/issues/164

I'm not sure if there's a way to test this short of merging it and seeing what fails.  WDYT @afrittoli ?

**Comment by vdemeester** [comment]
Also, https://github.com/google/ko/releases shows that 0.5.0 and 0.5.1 are targeting the same commit :sweat_smile:

**Pull request merged**
