### PR TITLE
Pin the version of gloud that we use

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Pin the version of gloud that we use

And since we're changing the image, use the alpine one which is
six times smaller than the debian based one.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind cleanup

### CODE REVIEW

**Comment by afrittoli** [comment]
> /lgtm
> On _nit_ question: any reason to go on `alpine` ? 😝

It's six times smaller than the debian one. I guess once it's cached it doesn't matter too much, still less code hopefully means fewer issues, vulnerabilities, complexity.

**Comment by vdemeester** [comment]
> It's six times smaller than the debian one. I guess once it's cached it doesn't matter too much, still less code hopefully means fewer issues, vulnerabilities, complexity.

On the downside, it's using `musl` which means it's "less" battle tested in a way… In any case, it's a nit :wink: 
/approve

**Pull request merged**
