### PR TITLE
Add doc for signing releases with Tekton Chains

### PR DESCRIPTION
**Pull request by priyawadhwa**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm
/cc @sbwsg (if you want to try that out with 0.27 😛 )

**Comment by jerop** [comment]
dropping lgtm to unblock tide

/lgtm cancel

**Comment by jerop** [comment]
plumbing-yamllint

**Comment by jerop** [comment]
re-lgtming now that tide is unblocked and plumbing-yamllint has passed 

/lgtm

**Comment by sbwsg** [comment]
> /cc @sbwsg (if you want to try that out with 0.27 😛 )

I didn't get to it as part of 0.27.0 but will give it a short with 0.27.1.  I created https://github.com/tektoncd/pipeline/issues/4153 to link back here and describe the work we need to do on the `publish-release` task first.

**Pull request merged**
