### PR TITLE
nightlies: update operator nightly pipelinerun

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Depends on https://github.com/tektoncd/operator/pull/898 to get in

/hold
/cc @tektoncd/operator-maintainers 

/kind misc

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
Depends on https://github.com/tektoncd/operator/pull/928 to get in as well.

**Comment by afrittoli** [comment]
@vdemeester the PR this depended on is merged. Is this ready to go?

**Comment by vdemeester** [comment]
> @vdemeester the PR this depended on is merged. Is this ready to go?

yes it is 👼🏼

**Comment by vdemeester** [comment]
oh this needs a rebase ?

**Comment by vdemeester** [comment]
ah crap.. made a mistake 😂

**Review by afrittoli — COMMENTED** [review]
/approve

**Pull request merged**
