### PR TITLE
Improve python tooling for adjustpermissions.py

### PR DESCRIPTION
**Pull request by lbernick**
# Changes

Added requirements.txt so users can easily install all required deps
(just pyyaml at the moment). Replace deprecated function pyyaml.load.
Add python and venv related files to gitignore.
Tested locally although I don't have permissions to actually run this.

This is in preparation for a follow-up PR adding a readonly option
to the adjustpermissions script (FYI @wlynch)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
Thank you!
/lgtm

**Comment by afrittoli** [comment]
Not sure what's going on with the EasyCLA check?

**Comment by vdemeester** [comment]
Close/Reopen force EasyCLA check 👼🏼 😈

**Pull request merged**
