### PR TITLE
Remove helm related jobs

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR removes helm related prow jobs.

There was almost no feedback during the last 2/3 months, so it's probably a sign of low interest.

Better keep this on the community side for now.
I will be happy to contribute again on this later if interest grows.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
@eddycharly any reason for removing those ? Things can stay for a while in experimental, I don't see why we would remove those, they are still useful for users I think.

**Comment by eddycharly** [comment]
@vdemeester you mean the jobs or the charts ?

There was not enough interest to get it done in the tekton org so that i would prefer not to let them mold here as nobody will maintain them.

On the other hand i will maintain charts in my github repo, i've setup the CI/CD elements that were missing here, the charts are published on a helm repo and are listed on helm hub/artifact hub.

IMO it's useless to keep them here, it can only do more harm than good.

**Comment by sbwsg** [comment]
> There was not enough interest to get it done in the tekton org so that i would prefer not to let them mold here as nobody will maintain them.

This makes sense to me. @vdemeester what do you think?

/approve

Needs a rebase before it can be merged.

**Comment by eddycharly** [comment]
@sbwsg forgot about it, i just rebased.

**Pull request merged**
