### PR TITLE
Increasing tekton/dashboard volume claim storage

### PR DESCRIPTION
**Pull request by kabhiibm**
# Changes

The Dashboard nightly tests are very flaky. It has been observed that it requires lot of memory when building required image while testing. We have seen following message:

image

/kind flake

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
Thank you @kabhiibm - please reach out to me if you need help with the CLA

**Comment by kabhiibm** [comment]
Tagging @savitaashture , @dlorenc for review. 
Thank you.

**Comment by AlanGreene** [comment]
I haven't seen any failures related to disk space since, not sure this is still needed.
Recent failures mostly seem related to network issues.

**Pull request closed without merging**
