### PR TITLE
Fix the file regex for kind e2e

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

The current is not valid. Set a regex so that we run the e2e test
when code or tests are altered.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [-] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

/kind bug

### CODE REVIEW

**Comment by afrittoli** [comment]
The tests are currently [skipped](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/pull-pipeline-kind-k8s-v1-20-e2e-p47s5?pipelineTask=check-git-files-changed&step=check-files-changed) because the check fails on invalid regex.

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
