### PR TITLE
Add observability configuration to pipeline

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Setup the pipeline controllers in dogfooding so that metrics for
prometheus are produced and scraped.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow

**Review by sbwsg — APPROVED** [review]

**Pull request merged**
