### PR TITLE
Bump go to 1.18.9 in "all" images.

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Going from 1.18.7 to the latest bugfix of go 1.18.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
@afrittoli somehow, something is wrong with `plumbing-image-build` pipeline 🤔

**Comment by vdemeester** [comment]
@afrittoli @abayer it's finally green 🎉 (thanks for fixing the CI)

**Comment by afrittoli** [comment]
> @afrittoli @abayer it's finally green 🎉 (thanks for fixing the CI)

The image build is now passing, however it runs only for the first image in the list.
This is because the taskloop controller was not maintained anymore, because we have matrix, but matrix is not functionally equivalent, it does not take a variable length array as input (like the results of the previous task), so the only options were:
- build all images all the time
- build the first image in the list

If we had one image changed per PR this would actually work, but on this PR we're only testing the first image.
I guess something like the old mario service could be used as a workaround for this kind of PRs, but I don't think it's in an healthy state

**Comment by afrittoli** [comment]
> /mario build tekton/images/kubectl kubectl:mario

Mario was migrated to use the pipeline-in-a-pod custom task which only understands `Runs` and the pipeline v0.44 now produces `CustomRun` so no chance for it to run as it is.

**Comment by vdemeester** [comment]
@afrittoli do you want me to split this PR into several ones ? (one per Dockerfile?)

**Comment by vdemeester** [comment]
Alright, I'll probably close and propose a PR per bump, and most likely will bump to go 1.19 as well.

**Pull request closed without merging**
