### PR TITLE
tekton/images: update kubectl and kustomize versions

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

- kubectl to 1.28.11
- kustomize to 5.4.2 (from 4.5.x)

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
@vdemeester rebase needed

**Comment by vdemeester** [comment]
@afrittoli done

**Review by afrittoli — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
