### PR TITLE
Update test-runner image in prow config

### PR DESCRIPTION
**Pull request by chuangw6**
# Changes

Fixes https://github.com/tektoncd/pipeline/issues/6992

Using the latest built image
`gcr.io/tekton-releases/dogfooding/test-runner@sha256:11dc05cf6e81786ce5935e43aad29a84d6b662804cb57f740c9fb3e1e73ff5f7`

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chuangw6** [comment]
cc @vdemeester @lbernick

**Review by lbernick — COMMENTED** [review]
/lgtm
Thanks Chuang!

**Comment by lbernick** [comment]
> Not sure if we should update all test-runner image to the latest in the prow config. If it's fine to change, please let me know.

Let's just fix the problem with existing CI, and we can upgrade other projects' prow config separately.

**Comment by vdemeester** [comment]
/approve
/lgtm

I agree with @lbernick. I think ideally we would have something like dependabot that updates the images, runs some "quick test" with components and gets automatically merged if it's green... But ideally, for this, we would probably want/need to have the CI setup directly in each components instead of here… (because here, we might need to update the image for pipeline to make CI green, but updating would break cli or another component.. which is definitely not an ideal situation)

**Pull request merged**
