### PR TITLE
 Install a pinned stable version of golangci-lint  instead of master

### LINKED ISSUE #125: Install golangci-lint from a release instead of master
When building the test-runner image, we are installing `golangci-lint` from master (using `RUN go get -u github.com/golangci/golangci-lint/cmd/golangci-lint`).

We should install it from a release version instead to make sure its behavior doesn't change implicitly when bumping the test-runner image.

/cc @chmouel 

Ref: tektoncd/pipeline#1634

/area test-infra

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

 Install golangci-lint from a pinned version

Let's install golangci-lint from a stable pinned version instead of master which
can brings weird CI breakage.

Closes #125

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [?] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
@chmouel similar to https://github.com/tektoncd/plumbing/pull/130#discussion_r351765456 I think we should use a fixed version (for both `tkn` and `golangci-lint`), with the nightly we should be good to go

**Comment by chmouel** [comment]
aye captain! 👨‍✈️ 

I amended and repushed, how do I get the mariobot to rebuild it ?

**Comment by afrittoli** [comment]
goomba at your service! </p>Cloud not build the requested image. Please check the <a href="http://35.222.249.224/?buildid=82ed24b7-f31b-48ba-add9-6154e52b49e9&namespace=mario">build logs</a>

**Comment by afrittoli** [comment]
luigi at your service! </p>Here is the image you requested: <a href="https://gcr.io/tekton-releases/dogfooding/test-runner:latest">built image</a>|<a href="http://35.222.249.224/?buildid=0b1be19e-691c-48a6-9bb5-a7ffa9374fc7&namespace=mario">build logs</a>

**Pull request merged**
