### PR TITLE
Deprecate adjustpermissions.py.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Permission changes are now handled by https://github.com/tektoncd/infra.

/kind cleanup

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by lbernick — COMMENTED** [review]
/lgtm

**Review by dibyom — APPROVED** [review]

**Pull request closed without merging**
