### PR TITLE
Move images to Golang 1.18.3

### PR DESCRIPTION
**Pull request by abayer**
# Changes

This has come up in a few different discussions the last few days, so let's just pull the trigger.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by imjasonh — COMMENTED** [review]
/lgtm

**Comment by abayer** [comment]
Image build failure is legit - `go get` fun. Working on it.

**Comment by abayer** [comment]
/hold

`plumbing-image-build` reports success before it's actually done, thanks to task loop stuff, so I'm holding this until I see that it's actually built all the images.

**Comment by afrittoli** [comment]
I believe we pinned all image versions in CI jobs so this should be fine and have no side effects until we go and pin the new versions. @vdemeester wdyt?

**Comment by abayer** [comment]
/hold cancel

ok, images all built.

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
