### PR TITLE
Add coverage build on cli

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This will force `tektoncd/cli` PR to have a certain amount of coverage (on new code)

/cc @chmouel @sthaha what do you think ?
/hold

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chmouel** [comment]
Is there a way to force it still ?  preivously in devtools we used  https://codecov.io/ which was working well and allowed to skip some PR that didn't need coverage

**Comment by vdemeester** [comment]
@chmouel there won't be a way to force it. We can however start with a lower number if we feel it's gonna be too much :angel: (see https://github.com/tektoncd/plumbing/pull/17/files#diff-406185368ba7839d1459d3d51424f104R184)

**Comment by chmouel** [comment]
I see but just to make sure I understand, is it only on "new code"? not on
a code fix? Does it detect code and make sure it's not something else?

**Comment by vdemeester** [comment]
> I see but just to make sure I understand, is it only on "new code"? not on a code fix? Does it detect code and make sure it's not something else?

Nah, it's not that smart :sweat_smile: it will validate the package that are modified, so if your ae doing a code fix on a non covered package, you will have to add tests :sweat_smile:

**Comment by vdemeester** [comment]
/hold
Let's try  :angel:

**Pull request merged**
