### PR TITLE
Correct the CLI for get ingress resource

### PR DESCRIPTION
**Pull request by gyliu513**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Comment by savitaashture** [comment]
@gyliu513

Can you please rebase PR
As CI check is failing for below reason 
```
yamllint bots/buildbot/config bots/mariobot/config pipelinerun-logs/config boskos gubernator prow robocat tekton
[Errno 2] No such file or directory: 'bots/buildbot/config'
```
because its looking for `bots` folder, your PR code doesn't have that :slightly_smiling_face:

**Comment by gyliu513** [comment]
@savitaashture sorry for late and rebased.

**Comment by gyliu513** [comment]
Not clear why CI continue fails due to following errors:

```
+ yamllint bots/buildbot/config bots/mariobot/config pipelinerun-logs/config boskos gubernator prow robocat tekton
[Errno 2] No such file or directory: 'bots/buildbot/config'
```

@savitaashture do you know what I need to do here? I thin the doc change should not trigger this error?

**Comment by vdemeester** [comment]
```bash
$ git fetch -p --all
# […]
$ git rebase upstream/master
$ git st
On branch 550--ingress
Your branch and 'gyliu513/ingress' have diverged,
and have 37 and 1 different commits each, respectively.

nothing to commit, working tree clean
```

It's not rebased (at least not on top of `upstream/master`). The error is because those path changed, and the configuration changed, but they are still there in you branch. @gyliu513 I can push the rebase if you want :stuck_out_tongue: (I think github allows us to do that)

**Comment by dibyom** [comment]
> yamllint bots/buildbot/config bots/mariobot/config pipelinerun-logs/config boskos gubernator prow robocat tekton
[Errno 2] No such file or directory: 'bots/buildbot/config'

The folder does exist tho : https://github.com/tektoncd/plumbing/tree/master/bots/buildbot/config

I think we might need to pull in the changes from master for the test to pass

**Comment by gyliu513** [comment]
A new PR opened at https://github.com/tektoncd/plumbing/pull/574

**Pull request closed without merging**
