### PR TITLE
Add documentation for using kind for e2e jobs

### PR DESCRIPTION
**Pull request by abayer**
# Changes

I needed to write this up!

/kind documentation

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
NIT: mind linking the new doc from some existing one to make it more discoverable?

**Review by vdemeester — APPROVED** [review]

**Comment by abayer** [comment]
> NIT: mind linking the new doc from some existing one to make it more discoverable?

Done - added to `docs/README.md`.

**Review by afrittoli — COMMENTED** [review]
Thank you!
/approve

**Pull request merged**
