### PR TITLE
Update dashboard integration test job

### PR DESCRIPTION
**Pull request by eddycharly**
# Changes

This PR updates dashboard integration test job.

I renamed the job to a simpler name as running multiple integration test jobs didn't work, there's no point in keeping the tested version in the job name.

I also the env variable that fixed the pipeline version to run integration tests against to let the integration test script decide the version to use.

/cc @AlanGreene 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by AlanGreene** [comment]
It would be good to include some more information in the commit message explaining why this change is being made, similar to the PR description.

/kind cleanup

**Comment by eddycharly** [comment]
I updated the commit description.

**Comment by AlanGreene** [comment]
Thanks @eddycharly 
/lgtm

**Pull request merged**
