### PR TITLE
Rename master -> maker 🎨

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

Since we are removing "master" terminology in other places, it felt like
changing it in this easter egg message made sense too.

(I still don't think @vdemeester is grumpy - or at least he hides it
well!! XD)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by bobcatfish** [comment]
/test plumbing-yamllint 
/test check-pr-has-kind-label 

(am i doing this right)

**Comment by bobcatfish** [comment]
image

oh neat! i think that my manually applying the config before https://github.com/tektoncd/plumbing/pull/672 was merged was undone by automation - the system is working! so it should fix itself ... but im gonna apply it manually again cuz im impatient XD

**Comment by bobcatfish** [comment]
command, y u do nothing

**Comment by vdemeester** [comment]
> (I still don't think @vdemeester is grumpy - or at least he hides it
> well!! XD)

I am grumpy with the code sometimes 😝

**Review by vdemeester — APPROVED** [review]
/meow
/lgtm

**Pull request merged**
