### PR TITLE
Remove pull-tekton-cli-integration-tests-0_10 jobs ✂️

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Those are not needed anymore as we are slowly moving away from
supporting v1alpha1 in the cli.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli @tektoncd/cli-maintainers 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Review by afrittoli — COMMENTED** [review]
/approve

**Pull request merged**
