### PR TITLE
Migrate install Tekton release CD service to workspaces

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Install Tekton release relies on the cluster PipelineResource
to target deployments of resources.

Migrate that to workspaces: a secret stored in the cluster bound
through a workspace is used to target the deployment.

Secrets have been preprovisioned on the cluster, their name is
tektoncd-, their type is kubeconfig.

See #887 for more details.

The change is implemented so that the template interface does not
change and thus all existing cronjobs are still valid as well as
the deployment script.

Fixes: #887

Added bonus, grep for `PipelineResource` on the plumbing repo yields no resources now!

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by lbernick** [comment]
/lgtm

nice!!

**Comment by abayer** [comment]
@afrittoli Hey, look, a bug in `plumbing-image-build` - see https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/taskruns/plumbing-image-build-l4dnb-images-build-00001-nt58r?step=build-and-push&view=details

It's trying to build the `koparse` image, but fails, because of this:
```
env:
  - name: FQ_DOCKER_FILE
    value: $(workspaces.source.path)/tekton/images/koparse/koparse/test_release.yaml
```
So it's trying to use `tekton/images/koparse/koparse` as the context and fails. Lemme see if I can fix.

**Comment by abayer** [comment]
And I have a fix in #1170

**Pull request merged**
