### PR TITLE
Fix podTemplate config for github-set-status

### PR DESCRIPTION
**Pull request by abayer**
# Changes

I'm more than a little ashamed that I missed this.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by abayer** [comment]
I've edited the `TriggerTemplate` by hand and am testing it out now.

**Comment by abayer** [comment]
/hold

Found another problem. Fixing it.

**Comment by abayer** [comment]
/hold cancel

It works!

**Review by afrittoli — COMMENTED** [review]
/approve
/lgtm

**Pull request merged**
