### PR TITLE
Enable nightly builds for Tekton Chains

### PR DESCRIPTION
**Pull request by lcarva**
# Changes

Set up nightly releases for Tekton Chains.

### CODE REVIEW

**Comment by lcarva** [comment]
I do not know how to test this locally. I based these changes on what is already setup for Tekton Pipelines. Any pointers would be greatly appreciated!

**Comment by lcarva** [comment]
@afrittoli, thanks for the `/ok-to-test`. I see that the checks still seem to be pending and there's a failure about missing `kind` label. Is there anything I can do from my end to address this?

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
