### PR TITLE
Add buildx-gcloud image to plumbing

### PR DESCRIPTION
**Pull request by barthy1**
# Changes

This image will be used to build multi-arch images with `docker buildx`
and push them to Google cloud.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by barthy1** [comment]
cc @afrittoli

**Comment by barthy1** [comment]
Is there a way to pass`plumbing-yamllint`? it seems it just hangs

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
Tests are triggered, but the check status is not reported for the `yamllint` job. 
I've been checking trigger controllers and event listeners, pipeline controllers and all seems ok. 
I checked past deployments to see if something changed but it doesn't look like it did... I'm not sure yet why the yamllint job is not working.

**Comment by afrittoli** [comment]
> /mario build tekton/images/buildx-gcloud buildx-gcloud:mario

:'( mario seems to be broken

**Review by afrittoli — COMMENTED** [review]
Thanks!
/lgtm

**Pull request merged**
