### PR TITLE
Remove implicit self approve

### PR DESCRIPTION
**Pull request by afrittoli**
The implicit self approve means that every PR submitted by an owner
may be inadvertently approved and merged by any member of the
tektoncd org with an /lgtm, where it should generally speaking be
reviewed and approved first by another member of the OWNERS team.
I think it's best to err on the safe side :)

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by bobcatfish** [comment]
Sounded like @abayer had strong feelings!

**Comment by bobcatfish** [comment]
p.s. alternatively, i wonder if the real problem is being more restrictive in the 'lgtm' powers??

**Comment by bobcatfish** [comment]
I could go either way on this one! Personally I think in most cases its fine for an OWNER to get approval and a random other org member lgtm - in my mind the real issue is around API changes (https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#approving-api-changes) and it would be nice to have something to make sure that API changes get the appropriate level of review. So my 2 cents are that removing the implicit self-approval doesn't really do much to address our real issues, but if folks want to go ahead with this then I'm okay with it!

**Comment by bobcatfish** [comment]
Latest in my stream of consciousness thoughts: maybe we can just try this and see how it goes?

/lgtm

(hee hee hee)

**Comment by afrittoli** [comment]
Heh, yeah, this would not be written in stone, but as we move towards 1.0 I think having two reviewers is probably not a bad thing, more likely to catch accidental breaking changes.

**Comment by vdemeester** [comment]
/hold cancel
:tada:

**Pull request merged**
