### PR TITLE
Cleanup the tekton/resources/release folder

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Remove unused resources:
- install_and_test_tekton_release.yaml
- test_tekton_release.yaml

Remove PipelineResources across the board, except for the
install_tekton_release.yaml resources (next PR).

The release log service was broken, bindings depended on old
release tasks. Refactor that service:
- remove the dedicated event listener, use the tekton-events
  event listener instead
- define a new triggerGroup in tekton-events that runs release
  specific triggers only
- define two new triggers, one for releases and one for
  nightly releases, which run the release-logs trigger template
  with the credentials to write to the respective bucket
- refactor the save logs task into a pipeline which does not
  use PipelineResources

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/meow

**Comment by abayer** [comment]
oops, I was late and hadn't reloaded. =)

**Pull request merged**
