### PR TITLE
community#418: Add org.yaml peribolos validation 🧙

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Add a pull-community-org-validation job on tektoncd/community
repository that will run peribolos in *dry-run* (not actually updating
the github org) to validate that the file is ok.

Should help keeping the file correct overtime 😛 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli @sbwsg @nikhil-thomas 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
Thanks! The new job looks good!
It won't actually deploy / work though unless you add the new file to `kustomization.yaml`.

**Comment by vdemeester** [comment]
> Thanks! The new job looks good!
> It won't actually deploy / work though unless you add the new file to `kustomization.yaml`.

ah ! I was sure I missed something 😹

**Comment by vdemeester** [comment]
@afrittoli updated 😉

**Review by afrittoli — COMMENTED** [review]
thanks!
/lgtm

**Pull request merged**
